// Code generated by Wire protocol buffer compiler, do not edit.
// Source: vpnhotspot.daemon.BridgeInterface in daemon.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package zy.hotspot.app.root.daemon

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.immutableCopyOf
import com.squareup.wire.`internal`.sanitize
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Suppress
import kotlin.collections.List
import okio.ByteString

public class BridgeInterface(
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 0,
  )
  public val name: String = "",
  members: List<String> = emptyList(),
  unknownFields: ByteString = ByteString.EMPTY,
) : Message<BridgeInterface, Nothing>(ADAPTER, unknownFields) {
  @field:WireField(
    tag = 2,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.REPEATED,
    schemaIndex = 1,
  )
  public val members: List<String> = immutableCopyOf("members", members)

  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is BridgeInterface) return false
    if (unknownFields != other.unknownFields) return false
    if (name != other.name) return false
    if (members != other.members) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + name.hashCode()
      result = result * 37 + members.hashCode()
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    result += """name=${sanitize(name)}"""
    if (members.isNotEmpty()) result += """members=${sanitize(members)}"""
    return result.joinToString(prefix = "BridgeInterface{", separator = ", ", postfix = "}")
  }

  public fun copy(
    name: String = this.name,
    members: List<String> = this.members,
    unknownFields: ByteString = this.unknownFields,
  ): BridgeInterface = BridgeInterface(name, members, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<BridgeInterface> = object : ProtoAdapter<BridgeInterface>(
      FieldEncoding.LENGTH_DELIMITED, 
      BridgeInterface::class, 
      "type.googleapis.com/vpnhotspot.daemon.BridgeInterface", 
      PROTO_3, 
      null, 
      "daemon.proto"
    ) {
      override fun encodedSize(`value`: BridgeInterface): Int {
        var size = value.unknownFields.size
        if (value.name != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(1, value.name)
        }
        size += ProtoAdapter.STRING.asRepeated().encodedSizeWithTag(2, value.members)
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: BridgeInterface) {
        if (value.name != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 1, value.name)
        }
        ProtoAdapter.STRING.asRepeated().encodeWithTag(writer, 2, value.members)
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: BridgeInterface) {
        writer.writeBytes(value.unknownFields)
        ProtoAdapter.STRING.asRepeated().encodeWithTag(writer, 2, value.members)
        if (value.name != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 1, value.name)
        }
      }

      override fun decode(reader: ProtoReader): BridgeInterface {
        var name: String = ""
        val members = mutableListOf<String>()
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> name = ProtoAdapter.STRING.decode(reader)
            2 -> members.add(ProtoAdapter.STRING.decode(reader))
            else -> reader.readUnknownField(tag)
          }
        }
        return BridgeInterface(
          name = name,
          members = members,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: BridgeInterface): BridgeInterface = value.copy(
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
