// Code generated by Wire protocol buffer compiler, do not edit.
// Source: vpnhotspot.daemon.CancelCommand in daemon.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package zy.hotspot.app.root.daemon

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.`internal`.JvmField
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Suppress
import okio.ByteString

public class CancelCommand(
  unknownFields: ByteString = ByteString.EMPTY,
) : Message<CancelCommand, Nothing>(ADAPTER, unknownFields) {
  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is CancelCommand) return false
    if (unknownFields != other.unknownFields) return false
    return true
  }

  override fun hashCode(): Int = unknownFields.hashCode()

  override fun toString(): String = "CancelCommand{}"

  public fun copy(unknownFields: ByteString = this.unknownFields): CancelCommand = CancelCommand(unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<CancelCommand> = object : ProtoAdapter<CancelCommand>(
      FieldEncoding.LENGTH_DELIMITED, 
      CancelCommand::class, 
      "type.googleapis.com/vpnhotspot.daemon.CancelCommand", 
      PROTO_3, 
      null, 
      "daemon.proto"
    ) {
      override fun encodedSize(`value`: CancelCommand): Int {
        var size = value.unknownFields.size
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: CancelCommand) {
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: CancelCommand) {
        writer.writeBytes(value.unknownFields)
      }

      override fun decode(reader: ProtoReader): CancelCommand {
        val unknownFields = reader.forEachTag(reader::readUnknownField)
        return CancelCommand(
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: CancelCommand): CancelCommand = value.copy(
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
