// Code generated by Wire protocol buffer compiler, do not edit.
// Source: vpnhotspot.daemon.CleanRoutingCommand in daemon.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package zy.hotspot.app.root.daemon

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.sanitize
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Suppress
import okio.ByteString

public class CleanRoutingCommand(
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "ipv6NatPrefixSeed",
    schemaIndex = 0,
  )
  public val ipv6_nat_prefix_seed: String = "",
  unknownFields: ByteString = ByteString.EMPTY,
) : Message<CleanRoutingCommand, Nothing>(ADAPTER, unknownFields) {
  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is CleanRoutingCommand) return false
    if (unknownFields != other.unknownFields) return false
    if (ipv6_nat_prefix_seed != other.ipv6_nat_prefix_seed) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + ipv6_nat_prefix_seed.hashCode()
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    result += """ipv6_nat_prefix_seed=${sanitize(ipv6_nat_prefix_seed)}"""
    return result.joinToString(prefix = "CleanRoutingCommand{", separator = ", ", postfix = "}")
  }

  public fun copy(ipv6_nat_prefix_seed: String = this.ipv6_nat_prefix_seed, unknownFields: ByteString = this.unknownFields): CleanRoutingCommand = CleanRoutingCommand(ipv6_nat_prefix_seed, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<CleanRoutingCommand> =
        object : ProtoAdapter<CleanRoutingCommand>(
      FieldEncoding.LENGTH_DELIMITED, 
      CleanRoutingCommand::class, 
      "type.googleapis.com/vpnhotspot.daemon.CleanRoutingCommand", 
      PROTO_3, 
      null, 
      "daemon.proto"
    ) {
      override fun encodedSize(`value`: CleanRoutingCommand): Int {
        var size = value.unknownFields.size
        if (value.ipv6_nat_prefix_seed != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(1, value.ipv6_nat_prefix_seed)
        }
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: CleanRoutingCommand) {
        if (value.ipv6_nat_prefix_seed != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 1, value.ipv6_nat_prefix_seed)
        }
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: CleanRoutingCommand) {
        writer.writeBytes(value.unknownFields)
        if (value.ipv6_nat_prefix_seed != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 1, value.ipv6_nat_prefix_seed)
        }
      }

      override fun decode(reader: ProtoReader): CleanRoutingCommand {
        var ipv6_nat_prefix_seed: String = ""
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> ipv6_nat_prefix_seed = ProtoAdapter.STRING.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return CleanRoutingCommand(
          ipv6_nat_prefix_seed = ipv6_nat_prefix_seed,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: CleanRoutingCommand): CleanRoutingCommand = value.copy(
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
