// Code generated by Wire protocol buffer compiler, do not edit.
// Source: vpnhotspot.daemon.ClientEnvelope in daemon.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package zy.hotspot.app.root.daemon

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.countNonNull
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Suppress
import okio.ByteString

public class ClientEnvelope(
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#UINT64",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "callId",
    schemaIndex = 0,
  )
  public val call_id: Long = 0L,
  @field:WireField(
    tag = 2,
    adapter = "zy.hotspot.app.root.daemon.CancelCommand#ADAPTER",
    oneofName = "command",
    schemaIndex = 1,
  )
  public val cancel: CancelCommand? = null,
  @field:WireField(
    tag = 3,
    adapter = "zy.hotspot.app.root.daemon.StartSessionCommand#ADAPTER",
    jsonName = "startSession",
    oneofName = "command",
    schemaIndex = 2,
  )
  public val start_session: StartSessionCommand? = null,
  @field:WireField(
    tag = 4,
    adapter = "zy.hotspot.app.root.daemon.ReplaceSessionCommand#ADAPTER",
    jsonName = "replaceSession",
    oneofName = "command",
    schemaIndex = 3,
  )
  public val replace_session: ReplaceSessionCommand? = null,
  @field:WireField(
    tag = 5,
    adapter = "zy.hotspot.app.root.daemon.ReadTrafficCountersCommand#ADAPTER",
    jsonName = "readTrafficCounters",
    oneofName = "command",
    schemaIndex = 4,
  )
  public val read_traffic_counters: ReadTrafficCountersCommand? = null,
  @field:WireField(
    tag = 6,
    adapter = "zy.hotspot.app.root.daemon.StartNeighbourMonitorCommand#ADAPTER",
    jsonName = "startNeighbourMonitor",
    oneofName = "command",
    schemaIndex = 5,
  )
  public val start_neighbour_monitor: StartNeighbourMonitorCommand? = null,
  @field:WireField(
    tag = 7,
    adapter = "zy.hotspot.app.root.daemon.CleanRoutingCommand#ADAPTER",
    jsonName = "cleanRouting",
    oneofName = "command",
    schemaIndex = 6,
  )
  public val clean_routing: CleanRoutingCommand? = null,
  @field:WireField(
    tag = 8,
    adapter = "zy.hotspot.app.root.daemon.ReplaceStaticAddressesCommand#ADAPTER",
    jsonName = "replaceStaticAddresses",
    oneofName = "command",
    schemaIndex = 7,
  )
  public val replace_static_addresses: ReplaceStaticAddressesCommand? = null,
  unknownFields: ByteString = ByteString.EMPTY,
) : Message<ClientEnvelope, Nothing>(ADAPTER, unknownFields) {
  init {
    require(countNonNull(cancel, start_session, replace_session, read_traffic_counters, start_neighbour_monitor, clean_routing, replace_static_addresses) <= 1) {
      "At most one of cancel, start_session, replace_session, read_traffic_counters, start_neighbour_monitor, clean_routing, replace_static_addresses may be non-null"
    }
  }

  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is ClientEnvelope) return false
    if (unknownFields != other.unknownFields) return false
    if (call_id != other.call_id) return false
    if (cancel != other.cancel) return false
    if (start_session != other.start_session) return false
    if (replace_session != other.replace_session) return false
    if (read_traffic_counters != other.read_traffic_counters) return false
    if (start_neighbour_monitor != other.start_neighbour_monitor) return false
    if (clean_routing != other.clean_routing) return false
    if (replace_static_addresses != other.replace_static_addresses) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + call_id.hashCode()
      result = result * 37 + (cancel?.hashCode() ?: 0)
      result = result * 37 + (start_session?.hashCode() ?: 0)
      result = result * 37 + (replace_session?.hashCode() ?: 0)
      result = result * 37 + (read_traffic_counters?.hashCode() ?: 0)
      result = result * 37 + (start_neighbour_monitor?.hashCode() ?: 0)
      result = result * 37 + (clean_routing?.hashCode() ?: 0)
      result = result * 37 + (replace_static_addresses?.hashCode() ?: 0)
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    result += """call_id=$call_id"""
    if (cancel != null) result += """cancel=$cancel"""
    if (start_session != null) result += """start_session=$start_session"""
    if (replace_session != null) result += """replace_session=$replace_session"""
    if (read_traffic_counters != null) result += """read_traffic_counters=$read_traffic_counters"""
    if (start_neighbour_monitor != null) result += """start_neighbour_monitor=$start_neighbour_monitor"""
    if (clean_routing != null) result += """clean_routing=$clean_routing"""
    if (replace_static_addresses != null) result += """replace_static_addresses=$replace_static_addresses"""
    return result.joinToString(prefix = "ClientEnvelope{", separator = ", ", postfix = "}")
  }

  public fun copy(
    call_id: Long = this.call_id,
    cancel: CancelCommand? = this.cancel,
    start_session: StartSessionCommand? = this.start_session,
    replace_session: ReplaceSessionCommand? = this.replace_session,
    read_traffic_counters: ReadTrafficCountersCommand? = this.read_traffic_counters,
    start_neighbour_monitor: StartNeighbourMonitorCommand? = this.start_neighbour_monitor,
    clean_routing: CleanRoutingCommand? = this.clean_routing,
    replace_static_addresses: ReplaceStaticAddressesCommand? = this.replace_static_addresses,
    unknownFields: ByteString = this.unknownFields,
  ): ClientEnvelope = ClientEnvelope(call_id, cancel, start_session, replace_session, read_traffic_counters, start_neighbour_monitor, clean_routing, replace_static_addresses, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<ClientEnvelope> = object : ProtoAdapter<ClientEnvelope>(
      FieldEncoding.LENGTH_DELIMITED, 
      ClientEnvelope::class, 
      "type.googleapis.com/vpnhotspot.daemon.ClientEnvelope", 
      PROTO_3, 
      null, 
      "daemon.proto"
    ) {
      override fun encodedSize(`value`: ClientEnvelope): Int {
        var size = value.unknownFields.size
        if (value.call_id != 0L) {
          size += ProtoAdapter.UINT64.encodedSizeWithTag(1, value.call_id)
        }
        size += CancelCommand.ADAPTER.encodedSizeWithTag(2, value.cancel)
        size += StartSessionCommand.ADAPTER.encodedSizeWithTag(3, value.start_session)
        size += ReplaceSessionCommand.ADAPTER.encodedSizeWithTag(4, value.replace_session)
        size += ReadTrafficCountersCommand.ADAPTER.encodedSizeWithTag(5, value.read_traffic_counters)
        size += StartNeighbourMonitorCommand.ADAPTER.encodedSizeWithTag(6, value.start_neighbour_monitor)
        size += CleanRoutingCommand.ADAPTER.encodedSizeWithTag(7, value.clean_routing)
        size += ReplaceStaticAddressesCommand.ADAPTER.encodedSizeWithTag(8, value.replace_static_addresses)
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: ClientEnvelope) {
        if (value.call_id != 0L) {
          ProtoAdapter.UINT64.encodeWithTag(writer, 1, value.call_id)
        }
        CancelCommand.ADAPTER.encodeWithTag(writer, 2, value.cancel)
        StartSessionCommand.ADAPTER.encodeWithTag(writer, 3, value.start_session)
        ReplaceSessionCommand.ADAPTER.encodeWithTag(writer, 4, value.replace_session)
        ReadTrafficCountersCommand.ADAPTER.encodeWithTag(writer, 5, value.read_traffic_counters)
        StartNeighbourMonitorCommand.ADAPTER.encodeWithTag(writer, 6, value.start_neighbour_monitor)
        CleanRoutingCommand.ADAPTER.encodeWithTag(writer, 7, value.clean_routing)
        ReplaceStaticAddressesCommand.ADAPTER.encodeWithTag(writer, 8, value.replace_static_addresses)
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: ClientEnvelope) {
        writer.writeBytes(value.unknownFields)
        ReplaceStaticAddressesCommand.ADAPTER.encodeWithTag(writer, 8, value.replace_static_addresses)
        CleanRoutingCommand.ADAPTER.encodeWithTag(writer, 7, value.clean_routing)
        StartNeighbourMonitorCommand.ADAPTER.encodeWithTag(writer, 6, value.start_neighbour_monitor)
        ReadTrafficCountersCommand.ADAPTER.encodeWithTag(writer, 5, value.read_traffic_counters)
        ReplaceSessionCommand.ADAPTER.encodeWithTag(writer, 4, value.replace_session)
        StartSessionCommand.ADAPTER.encodeWithTag(writer, 3, value.start_session)
        CancelCommand.ADAPTER.encodeWithTag(writer, 2, value.cancel)
        if (value.call_id != 0L) {
          ProtoAdapter.UINT64.encodeWithTag(writer, 1, value.call_id)
        }
      }

      override fun decode(reader: ProtoReader): ClientEnvelope {
        var call_id: Long = 0L
        var cancel: CancelCommand? = null
        var start_session: StartSessionCommand? = null
        var replace_session: ReplaceSessionCommand? = null
        var read_traffic_counters: ReadTrafficCountersCommand? = null
        var start_neighbour_monitor: StartNeighbourMonitorCommand? = null
        var clean_routing: CleanRoutingCommand? = null
        var replace_static_addresses: ReplaceStaticAddressesCommand? = null
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> call_id = ProtoAdapter.UINT64.decode(reader)
            2 -> cancel = CancelCommand.ADAPTER.decode(reader)
            3 -> start_session = StartSessionCommand.ADAPTER.decode(reader)
            4 -> replace_session = ReplaceSessionCommand.ADAPTER.decode(reader)
            5 -> read_traffic_counters = ReadTrafficCountersCommand.ADAPTER.decode(reader)
            6 -> start_neighbour_monitor = StartNeighbourMonitorCommand.ADAPTER.decode(reader)
            7 -> clean_routing = CleanRoutingCommand.ADAPTER.decode(reader)
            8 -> replace_static_addresses = ReplaceStaticAddressesCommand.ADAPTER.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return ClientEnvelope(
          call_id = call_id,
          cancel = cancel,
          start_session = start_session,
          replace_session = replace_session,
          read_traffic_counters = read_traffic_counters,
          start_neighbour_monitor = start_neighbour_monitor,
          clean_routing = clean_routing,
          replace_static_addresses = replace_static_addresses,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: ClientEnvelope): ClientEnvelope = value.copy(
        cancel = value.cancel?.let(CancelCommand.ADAPTER::redact),
        start_session = value.start_session?.let(StartSessionCommand.ADAPTER::redact),
        replace_session = value.replace_session?.let(ReplaceSessionCommand.ADAPTER::redact),
        read_traffic_counters = value.read_traffic_counters?.let(ReadTrafficCountersCommand.ADAPTER::redact),
        start_neighbour_monitor = value.start_neighbour_monitor?.let(StartNeighbourMonitorCommand.ADAPTER::redact),
        clean_routing = value.clean_routing?.let(CleanRoutingCommand.ADAPTER::redact),
        replace_static_addresses = value.replace_static_addresses?.let(ReplaceStaticAddressesCommand.ADAPTER::redact),
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
