// Code generated by Wire protocol buffer compiler, do not edit.
// Source: vpnhotspot.daemon.ClientConfig in daemon.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package zy.hotspot.app.root.daemon

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.immutableCopyOf
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Suppress
import kotlin.collections.List
import okio.ByteString

public class ClientConfig(
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#BYTES",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 0,
  )
  public val mac: ByteString = ByteString.EMPTY,
  ipv4: List<ByteString> = emptyList(),
  unknownFields: ByteString = ByteString.EMPTY,
) : Message<ClientConfig, Nothing>(ADAPTER, unknownFields) {
  @field:WireField(
    tag = 2,
    adapter = "com.squareup.wire.ProtoAdapter#BYTES",
    label = WireField.Label.REPEATED,
    schemaIndex = 1,
  )
  public val ipv4: List<ByteString> = immutableCopyOf("ipv4", ipv4)

  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is ClientConfig) return false
    if (unknownFields != other.unknownFields) return false
    if (mac != other.mac) return false
    if (ipv4 != other.ipv4) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + mac.hashCode()
      result = result * 37 + ipv4.hashCode()
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    result += """mac=$mac"""
    if (ipv4.isNotEmpty()) result += """ipv4=$ipv4"""
    return result.joinToString(prefix = "ClientConfig{", separator = ", ", postfix = "}")
  }

  public fun copy(
    mac: ByteString = this.mac,
    ipv4: List<ByteString> = this.ipv4,
    unknownFields: ByteString = this.unknownFields,
  ): ClientConfig = ClientConfig(mac, ipv4, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<ClientConfig> = object : ProtoAdapter<ClientConfig>(
      FieldEncoding.LENGTH_DELIMITED, 
      ClientConfig::class, 
      "type.googleapis.com/vpnhotspot.daemon.ClientConfig", 
      PROTO_3, 
      null, 
      "daemon.proto"
    ) {
      override fun encodedSize(`value`: ClientConfig): Int {
        var size = value.unknownFields.size
        if (value.mac != okio.ByteString.EMPTY) {
          size += ProtoAdapter.BYTES.encodedSizeWithTag(1, value.mac)
        }
        size += ProtoAdapter.BYTES.asRepeated().encodedSizeWithTag(2, value.ipv4)
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: ClientConfig) {
        if (value.mac != okio.ByteString.EMPTY) {
          ProtoAdapter.BYTES.encodeWithTag(writer, 1, value.mac)
        }
        ProtoAdapter.BYTES.asRepeated().encodeWithTag(writer, 2, value.ipv4)
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: ClientConfig) {
        writer.writeBytes(value.unknownFields)
        ProtoAdapter.BYTES.asRepeated().encodeWithTag(writer, 2, value.ipv4)
        if (value.mac != okio.ByteString.EMPTY) {
          ProtoAdapter.BYTES.encodeWithTag(writer, 1, value.mac)
        }
      }

      override fun decode(reader: ProtoReader): ClientConfig {
        var mac: ByteString = ByteString.EMPTY
        val ipv4 = mutableListOf<ByteString>()
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> mac = ProtoAdapter.BYTES.decode(reader)
            2 -> ipv4.add(ProtoAdapter.BYTES.decode(reader))
            else -> reader.readUnknownField(tag)
          }
        }
        return ClientConfig(
          mac = mac,
          ipv4 = ipv4,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: ClientConfig): ClientConfig = value.copy(
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
