// Code generated by Wire protocol buffer compiler, do not edit.
// Source: vpnhotspot.daemon.DaemonEnvelope in daemon.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package zy.hotspot.app.root.daemon

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.countNonNull
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Suppress
import okio.ByteString

public class DaemonEnvelope(
  @field:WireField(
    tag = 1,
    adapter = "zy.hotspot.app.root.daemon.ReplyFrame#ADAPTER",
    oneofName = "frame",
    schemaIndex = 0,
  )
  public val reply: ReplyFrame? = null,
  @field:WireField(
    tag = 2,
    adapter = "zy.hotspot.app.root.daemon.EventFrame#ADAPTER",
    oneofName = "frame",
    schemaIndex = 1,
  )
  public val event: EventFrame? = null,
  @field:WireField(
    tag = 3,
    adapter = "zy.hotspot.app.root.daemon.ErrorFrame#ADAPTER",
    oneofName = "frame",
    schemaIndex = 2,
  )
  public val error: ErrorFrame? = null,
  @field:WireField(
    tag = 4,
    adapter = "zy.hotspot.app.root.daemon.NonFatalFrame#ADAPTER",
    jsonName = "nonFatal",
    oneofName = "frame",
    schemaIndex = 3,
  )
  public val non_fatal: NonFatalFrame? = null,
  @field:WireField(
    tag = 5,
    adapter = "zy.hotspot.app.root.daemon.CompleteFrame#ADAPTER",
    oneofName = "frame",
    schemaIndex = 4,
  )
  public val complete: CompleteFrame? = null,
  unknownFields: ByteString = ByteString.EMPTY,
) : Message<DaemonEnvelope, Nothing>(ADAPTER, unknownFields) {
  init {
    require(countNonNull(reply, event, error, non_fatal, complete) <= 1) {
      "At most one of reply, event, error, non_fatal, complete may be non-null"
    }
  }

  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is DaemonEnvelope) return false
    if (unknownFields != other.unknownFields) return false
    if (reply != other.reply) return false
    if (event != other.event) return false
    if (error != other.error) return false
    if (non_fatal != other.non_fatal) return false
    if (complete != other.complete) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + (reply?.hashCode() ?: 0)
      result = result * 37 + (event?.hashCode() ?: 0)
      result = result * 37 + (error?.hashCode() ?: 0)
      result = result * 37 + (non_fatal?.hashCode() ?: 0)
      result = result * 37 + (complete?.hashCode() ?: 0)
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    if (reply != null) result += """reply=$reply"""
    if (event != null) result += """event=$event"""
    if (error != null) result += """error=$error"""
    if (non_fatal != null) result += """non_fatal=$non_fatal"""
    if (complete != null) result += """complete=$complete"""
    return result.joinToString(prefix = "DaemonEnvelope{", separator = ", ", postfix = "}")
  }

  public fun copy(
    reply: ReplyFrame? = this.reply,
    event: EventFrame? = this.event,
    error: ErrorFrame? = this.error,
    non_fatal: NonFatalFrame? = this.non_fatal,
    complete: CompleteFrame? = this.complete,
    unknownFields: ByteString = this.unknownFields,
  ): DaemonEnvelope = DaemonEnvelope(reply, event, error, non_fatal, complete, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<DaemonEnvelope> = object : ProtoAdapter<DaemonEnvelope>(
      FieldEncoding.LENGTH_DELIMITED, 
      DaemonEnvelope::class, 
      "type.googleapis.com/vpnhotspot.daemon.DaemonEnvelope", 
      PROTO_3, 
      null, 
      "daemon.proto"
    ) {
      override fun encodedSize(`value`: DaemonEnvelope): Int {
        var size = value.unknownFields.size
        size += ReplyFrame.ADAPTER.encodedSizeWithTag(1, value.reply)
        size += EventFrame.ADAPTER.encodedSizeWithTag(2, value.event)
        size += ErrorFrame.ADAPTER.encodedSizeWithTag(3, value.error)
        size += NonFatalFrame.ADAPTER.encodedSizeWithTag(4, value.non_fatal)
        size += CompleteFrame.ADAPTER.encodedSizeWithTag(5, value.complete)
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: DaemonEnvelope) {
        ReplyFrame.ADAPTER.encodeWithTag(writer, 1, value.reply)
        EventFrame.ADAPTER.encodeWithTag(writer, 2, value.event)
        ErrorFrame.ADAPTER.encodeWithTag(writer, 3, value.error)
        NonFatalFrame.ADAPTER.encodeWithTag(writer, 4, value.non_fatal)
        CompleteFrame.ADAPTER.encodeWithTag(writer, 5, value.complete)
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: DaemonEnvelope) {
        writer.writeBytes(value.unknownFields)
        CompleteFrame.ADAPTER.encodeWithTag(writer, 5, value.complete)
        NonFatalFrame.ADAPTER.encodeWithTag(writer, 4, value.non_fatal)
        ErrorFrame.ADAPTER.encodeWithTag(writer, 3, value.error)
        EventFrame.ADAPTER.encodeWithTag(writer, 2, value.event)
        ReplyFrame.ADAPTER.encodeWithTag(writer, 1, value.reply)
      }

      override fun decode(reader: ProtoReader): DaemonEnvelope {
        var reply: ReplyFrame? = null
        var event: EventFrame? = null
        var error: ErrorFrame? = null
        var non_fatal: NonFatalFrame? = null
        var complete: CompleteFrame? = null
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> reply = ReplyFrame.ADAPTER.decode(reader)
            2 -> event = EventFrame.ADAPTER.decode(reader)
            3 -> error = ErrorFrame.ADAPTER.decode(reader)
            4 -> non_fatal = NonFatalFrame.ADAPTER.decode(reader)
            5 -> complete = CompleteFrame.ADAPTER.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return DaemonEnvelope(
          reply = reply,
          event = event,
          error = error,
          non_fatal = non_fatal,
          complete = complete,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: DaemonEnvelope): DaemonEnvelope = value.copy(
        reply = value.reply?.let(ReplyFrame.ADAPTER::redact),
        event = value.event?.let(EventFrame.ADAPTER::redact),
        error = value.error?.let(ErrorFrame.ADAPTER::redact),
        non_fatal = value.non_fatal?.let(NonFatalFrame.ADAPTER::redact),
        complete = value.complete?.let(CompleteFrame.ADAPTER::redact),
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
