// Code generated by Wire protocol buffer compiler, do not edit.
// Source: vpnhotspot.daemon.DaemonTrafficSource in daemon.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package zy.hotspot.app.root.daemon

import com.squareup.wire.EnumAdapter
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireEnum
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.JvmStatic
import kotlin.ConsistentCopyVisibility
import kotlin.Int
import kotlin.Suppress

public sealed class DaemonTrafficSource(
  override val `value`: Int,
) : WireEnum {
  public data object DAEMON_TRAFFIC_SOURCE_UNSPECIFIED : DaemonTrafficSource(0)

  public data object DAEMON_TRAFFIC_SOURCE_DNS : DaemonTrafficSource(1)

  public data object DAEMON_TRAFFIC_SOURCE_NAT66_TCP : DaemonTrafficSource(2)

  public data object DAEMON_TRAFFIC_SOURCE_NAT66_UDP : DaemonTrafficSource(3)

  public data object DAEMON_TRAFFIC_SOURCE_NAT66_ICMPV6 : DaemonTrafficSource(4)

  @ConsistentCopyVisibility
  public data class Unrecognized internal constructor(
    override val `value`: Int,
  ) : DaemonTrafficSource(value)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<DaemonTrafficSource> =
        object : EnumAdapter<DaemonTrafficSource>(
      DaemonTrafficSource::class, 
      PROTO_3, 
      DaemonTrafficSource.DAEMON_TRAFFIC_SOURCE_UNSPECIFIED
    ) {
      override fun fromValue(`value`: Int): DaemonTrafficSource? = DaemonTrafficSource.fromValue(`value`)
    }

    @JvmStatic
    public fun fromValue(`value`: Int): DaemonTrafficSource = when (`value`) {
      0 -> DAEMON_TRAFFIC_SOURCE_UNSPECIFIED
      1 -> DAEMON_TRAFFIC_SOURCE_DNS
      2 -> DAEMON_TRAFFIC_SOURCE_NAT66_TCP
      3 -> DAEMON_TRAFFIC_SOURCE_NAT66_UDP
      4 -> DAEMON_TRAFFIC_SOURCE_NAT66_ICMPV6
      else -> Unrecognized(`value`)
    }
  }
}
