// Code generated by Wire protocol buffer compiler, do not edit.
// Source: vpnhotspot.daemon.DaemonErrorReport in daemon.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package zy.hotspot.app.root.daemon

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.immutableCopyOf
import com.squareup.wire.`internal`.redactElements
import com.squareup.wire.`internal`.sanitize
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Suppress
import kotlin.collections.List
import okio.ByteString

public class DaemonErrorReport(
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 0,
  )
  public val context: String = "",
  @field:WireField(
    tag = 2,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 1,
  )
  public val message: String = "",
  @field:WireField(
    tag = 3,
    adapter = "com.squareup.wire.ProtoAdapter#INT32",
    schemaIndex = 2,
  )
  public val errno: Int? = null,
  @field:WireField(
    tag = 4,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 3,
  )
  public val kind: String = "",
  @field:WireField(
    tag = 5,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    declaredName = "file",
    schemaIndex = 4,
  )
  public val file_: String = "",
  @field:WireField(
    tag = 6,
    adapter = "com.squareup.wire.ProtoAdapter#UINT32",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 5,
  )
  public val line: Int = 0,
  @field:WireField(
    tag = 7,
    adapter = "com.squareup.wire.ProtoAdapter#UINT32",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 6,
  )
  public val column: Int = 0,
  @field:WireField(
    tag = 8,
    adapter = "com.squareup.wire.ProtoAdapter#UINT32",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 7,
  )
  public val pid: Int = 0,
  details: List<ErrorDetail> = emptyList(),
  unknownFields: ByteString = ByteString.EMPTY,
) : Message<DaemonErrorReport, Nothing>(ADAPTER, unknownFields) {
  @field:WireField(
    tag = 9,
    adapter = "zy.hotspot.app.root.daemon.ErrorDetail#ADAPTER",
    label = WireField.Label.REPEATED,
    schemaIndex = 8,
  )
  public val details: List<ErrorDetail> = immutableCopyOf("details", details)

  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is DaemonErrorReport) return false
    if (unknownFields != other.unknownFields) return false
    if (context != other.context) return false
    if (message != other.message) return false
    if (errno != other.errno) return false
    if (kind != other.kind) return false
    if (file_ != other.file_) return false
    if (line != other.line) return false
    if (column != other.column) return false
    if (pid != other.pid) return false
    if (details != other.details) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + context.hashCode()
      result = result * 37 + message.hashCode()
      result = result * 37 + (errno?.hashCode() ?: 0)
      result = result * 37 + kind.hashCode()
      result = result * 37 + file_.hashCode()
      result = result * 37 + line.hashCode()
      result = result * 37 + column.hashCode()
      result = result * 37 + pid.hashCode()
      result = result * 37 + details.hashCode()
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    result += """context=${sanitize(context)}"""
    result += """message=${sanitize(message)}"""
    if (errno != null) result += """errno=$errno"""
    result += """kind=${sanitize(kind)}"""
    result += """file_=${sanitize(file_)}"""
    result += """line=$line"""
    result += """column=$column"""
    result += """pid=$pid"""
    if (details.isNotEmpty()) result += """details=$details"""
    return result.joinToString(prefix = "DaemonErrorReport{", separator = ", ", postfix = "}")
  }

  public fun copy(
    context: String = this.context,
    message: String = this.message,
    errno: Int? = this.errno,
    kind: String = this.kind,
    file_: String = this.file_,
    line: Int = this.line,
    column: Int = this.column,
    pid: Int = this.pid,
    details: List<ErrorDetail> = this.details,
    unknownFields: ByteString = this.unknownFields,
  ): DaemonErrorReport = DaemonErrorReport(context, message, errno, kind, file_, line, column, pid, details, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<DaemonErrorReport> = object : ProtoAdapter<DaemonErrorReport>(
      FieldEncoding.LENGTH_DELIMITED, 
      DaemonErrorReport::class, 
      "type.googleapis.com/vpnhotspot.daemon.DaemonErrorReport", 
      PROTO_3, 
      null, 
      "daemon.proto"
    ) {
      override fun encodedSize(`value`: DaemonErrorReport): Int {
        var size = value.unknownFields.size
        if (value.context != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(1, value.context)
        }
        if (value.message != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(2, value.message)
        }
        size += ProtoAdapter.INT32.encodedSizeWithTag(3, value.errno)
        if (value.kind != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(4, value.kind)
        }
        if (value.file_ != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(5, value.file_)
        }
        if (value.line != 0) {
          size += ProtoAdapter.UINT32.encodedSizeWithTag(6, value.line)
        }
        if (value.column != 0) {
          size += ProtoAdapter.UINT32.encodedSizeWithTag(7, value.column)
        }
        if (value.pid != 0) {
          size += ProtoAdapter.UINT32.encodedSizeWithTag(8, value.pid)
        }
        size += ErrorDetail.ADAPTER.asRepeated().encodedSizeWithTag(9, value.details)
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: DaemonErrorReport) {
        if (value.context != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 1, value.context)
        }
        if (value.message != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 2, value.message)
        }
        ProtoAdapter.INT32.encodeWithTag(writer, 3, value.errno)
        if (value.kind != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 4, value.kind)
        }
        if (value.file_ != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 5, value.file_)
        }
        if (value.line != 0) {
          ProtoAdapter.UINT32.encodeWithTag(writer, 6, value.line)
        }
        if (value.column != 0) {
          ProtoAdapter.UINT32.encodeWithTag(writer, 7, value.column)
        }
        if (value.pid != 0) {
          ProtoAdapter.UINT32.encodeWithTag(writer, 8, value.pid)
        }
        ErrorDetail.ADAPTER.asRepeated().encodeWithTag(writer, 9, value.details)
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: DaemonErrorReport) {
        writer.writeBytes(value.unknownFields)
        ErrorDetail.ADAPTER.asRepeated().encodeWithTag(writer, 9, value.details)
        if (value.pid != 0) {
          ProtoAdapter.UINT32.encodeWithTag(writer, 8, value.pid)
        }
        if (value.column != 0) {
          ProtoAdapter.UINT32.encodeWithTag(writer, 7, value.column)
        }
        if (value.line != 0) {
          ProtoAdapter.UINT32.encodeWithTag(writer, 6, value.line)
        }
        if (value.file_ != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 5, value.file_)
        }
        if (value.kind != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 4, value.kind)
        }
        ProtoAdapter.INT32.encodeWithTag(writer, 3, value.errno)
        if (value.message != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 2, value.message)
        }
        if (value.context != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 1, value.context)
        }
      }

      override fun decode(reader: ProtoReader): DaemonErrorReport {
        var context: String = ""
        var message: String = ""
        var errno: Int? = null
        var kind: String = ""
        var file_: String = ""
        var line: Int = 0
        var column: Int = 0
        var pid: Int = 0
        val details = mutableListOf<ErrorDetail>()
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> context = ProtoAdapter.STRING.decode(reader)
            2 -> message = ProtoAdapter.STRING.decode(reader)
            3 -> errno = ProtoAdapter.INT32.decode(reader)
            4 -> kind = ProtoAdapter.STRING.decode(reader)
            5 -> file_ = ProtoAdapter.STRING.decode(reader)
            6 -> line = ProtoAdapter.UINT32.decode(reader)
            7 -> column = ProtoAdapter.UINT32.decode(reader)
            8 -> pid = ProtoAdapter.UINT32.decode(reader)
            9 -> details.add(ErrorDetail.ADAPTER.decode(reader))
            else -> reader.readUnknownField(tag)
          }
        }
        return DaemonErrorReport(
          context = context,
          message = message,
          errno = errno,
          kind = kind,
          file_ = file_,
          line = line,
          column = column,
          pid = pid,
          details = details,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: DaemonErrorReport): DaemonErrorReport = value.copy(
        details = value.details.redactElements(ErrorDetail.ADAPTER),
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
