// Code generated by Wire protocol buffer compiler, do not edit.
// Source: vpnhotspot.daemon.ErrorDetail in daemon.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package zy.hotspot.app.root.daemon

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.sanitize
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Suppress
import okio.ByteString

public class ErrorDetail(
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 0,
  )
  public val key: String = "",
  @field:WireField(
    tag = 2,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    declaredName = "value",
    schemaIndex = 1,
  )
  public val value_: String = "",
  unknownFields: ByteString = ByteString.EMPTY,
) : Message<ErrorDetail, Nothing>(ADAPTER, unknownFields) {
  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is ErrorDetail) return false
    if (unknownFields != other.unknownFields) return false
    if (key != other.key) return false
    if (value_ != other.value_) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + key.hashCode()
      result = result * 37 + value_.hashCode()
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    result += """key=${sanitize(key)}"""
    result += """value_=${sanitize(value_)}"""
    return result.joinToString(prefix = "ErrorDetail{", separator = ", ", postfix = "}")
  }

  public fun copy(
    key: String = this.key,
    value_: String = this.value_,
    unknownFields: ByteString = this.unknownFields,
  ): ErrorDetail = ErrorDetail(key, value_, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<ErrorDetail> = object : ProtoAdapter<ErrorDetail>(
      FieldEncoding.LENGTH_DELIMITED, 
      ErrorDetail::class, 
      "type.googleapis.com/vpnhotspot.daemon.ErrorDetail", 
      PROTO_3, 
      null, 
      "daemon.proto"
    ) {
      override fun encodedSize(`value`: ErrorDetail): Int {
        var size = value.unknownFields.size
        if (value.key != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(1, value.key)
        }
        if (value.value_ != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(2, value.value_)
        }
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: ErrorDetail) {
        if (value.key != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 1, value.key)
        }
        if (value.value_ != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 2, value.value_)
        }
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: ErrorDetail) {
        writer.writeBytes(value.unknownFields)
        if (value.value_ != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 2, value.value_)
        }
        if (value.key != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 1, value.key)
        }
      }

      override fun decode(reader: ProtoReader): ErrorDetail {
        var key: String = ""
        var value_: String = ""
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> key = ProtoAdapter.STRING.decode(reader)
            2 -> value_ = ProtoAdapter.STRING.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return ErrorDetail(
          key = key,
          value_ = value_,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: ErrorDetail): ErrorDetail = value.copy(
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
