// Code generated by Wire protocol buffer compiler, do not edit.
// Source: vpnhotspot.daemon.EventFrame in daemon.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package zy.hotspot.app.root.daemon

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.countNonNull
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Suppress
import okio.ByteString

public class EventFrame(
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#UINT64",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "callId",
    schemaIndex = 0,
  )
  public val call_id: Long = 0L,
  @field:WireField(
    tag = 2,
    adapter = "zy.hotspot.app.root.daemon.Ack#ADAPTER",
    oneofName = "payload",
    schemaIndex = 1,
  )
  public val ack: Ack? = null,
  @field:WireField(
    tag = 3,
    adapter = "zy.hotspot.app.root.daemon.NeighbourMonitorUpdate#ADAPTER",
    jsonName = "neighbourMonitor",
    oneofName = "payload",
    schemaIndex = 2,
  )
  public val neighbour_monitor: NeighbourMonitorUpdate? = null,
  @field:WireField(
    tag = 4,
    adapter = "zy.hotspot.app.root.daemon.IpSecForwardPolicyRequest#ADAPTER",
    jsonName = "ipsecForwardPolicy",
    oneofName = "payload",
    schemaIndex = 3,
  )
  public val ipsec_forward_policy: IpSecForwardPolicyRequest? = null,
  unknownFields: ByteString = ByteString.EMPTY,
) : Message<EventFrame, Nothing>(ADAPTER, unknownFields) {
  init {
    require(countNonNull(ack, neighbour_monitor, ipsec_forward_policy) <= 1) {
      "At most one of ack, neighbour_monitor, ipsec_forward_policy may be non-null"
    }
  }

  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is EventFrame) return false
    if (unknownFields != other.unknownFields) return false
    if (call_id != other.call_id) return false
    if (ack != other.ack) return false
    if (neighbour_monitor != other.neighbour_monitor) return false
    if (ipsec_forward_policy != other.ipsec_forward_policy) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + call_id.hashCode()
      result = result * 37 + (ack?.hashCode() ?: 0)
      result = result * 37 + (neighbour_monitor?.hashCode() ?: 0)
      result = result * 37 + (ipsec_forward_policy?.hashCode() ?: 0)
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    result += """call_id=$call_id"""
    if (ack != null) result += """ack=$ack"""
    if (neighbour_monitor != null) result += """neighbour_monitor=$neighbour_monitor"""
    if (ipsec_forward_policy != null) result += """ipsec_forward_policy=$ipsec_forward_policy"""
    return result.joinToString(prefix = "EventFrame{", separator = ", ", postfix = "}")
  }

  public fun copy(
    call_id: Long = this.call_id,
    ack: Ack? = this.ack,
    neighbour_monitor: NeighbourMonitorUpdate? = this.neighbour_monitor,
    ipsec_forward_policy: IpSecForwardPolicyRequest? = this.ipsec_forward_policy,
    unknownFields: ByteString = this.unknownFields,
  ): EventFrame = EventFrame(call_id, ack, neighbour_monitor, ipsec_forward_policy, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<EventFrame> = object : ProtoAdapter<EventFrame>(
      FieldEncoding.LENGTH_DELIMITED, 
      EventFrame::class, 
      "type.googleapis.com/vpnhotspot.daemon.EventFrame", 
      PROTO_3, 
      null, 
      "daemon.proto"
    ) {
      override fun encodedSize(`value`: EventFrame): Int {
        var size = value.unknownFields.size
        if (value.call_id != 0L) {
          size += ProtoAdapter.UINT64.encodedSizeWithTag(1, value.call_id)
        }
        size += Ack.ADAPTER.encodedSizeWithTag(2, value.ack)
        size += NeighbourMonitorUpdate.ADAPTER.encodedSizeWithTag(3, value.neighbour_monitor)
        size += IpSecForwardPolicyRequest.ADAPTER.encodedSizeWithTag(4, value.ipsec_forward_policy)
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: EventFrame) {
        if (value.call_id != 0L) {
          ProtoAdapter.UINT64.encodeWithTag(writer, 1, value.call_id)
        }
        Ack.ADAPTER.encodeWithTag(writer, 2, value.ack)
        NeighbourMonitorUpdate.ADAPTER.encodeWithTag(writer, 3, value.neighbour_monitor)
        IpSecForwardPolicyRequest.ADAPTER.encodeWithTag(writer, 4, value.ipsec_forward_policy)
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: EventFrame) {
        writer.writeBytes(value.unknownFields)
        IpSecForwardPolicyRequest.ADAPTER.encodeWithTag(writer, 4, value.ipsec_forward_policy)
        NeighbourMonitorUpdate.ADAPTER.encodeWithTag(writer, 3, value.neighbour_monitor)
        Ack.ADAPTER.encodeWithTag(writer, 2, value.ack)
        if (value.call_id != 0L) {
          ProtoAdapter.UINT64.encodeWithTag(writer, 1, value.call_id)
        }
      }

      override fun decode(reader: ProtoReader): EventFrame {
        var call_id: Long = 0L
        var ack: Ack? = null
        var neighbour_monitor: NeighbourMonitorUpdate? = null
        var ipsec_forward_policy: IpSecForwardPolicyRequest? = null
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> call_id = ProtoAdapter.UINT64.decode(reader)
            2 -> ack = Ack.ADAPTER.decode(reader)
            3 -> neighbour_monitor = NeighbourMonitorUpdate.ADAPTER.decode(reader)
            4 -> ipsec_forward_policy = IpSecForwardPolicyRequest.ADAPTER.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return EventFrame(
          call_id = call_id,
          ack = ack,
          neighbour_monitor = neighbour_monitor,
          ipsec_forward_policy = ipsec_forward_policy,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: EventFrame): EventFrame = value.copy(
        ack = value.ack?.let(Ack.ADAPTER::redact),
        neighbour_monitor = value.neighbour_monitor?.let(NeighbourMonitorUpdate.ADAPTER::redact),
        ipsec_forward_policy = value.ipsec_forward_policy?.let(IpSecForwardPolicyRequest.ADAPTER::redact),
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
