// Code generated by Wire protocol buffer compiler, do not edit.
// Source: vpnhotspot.daemon.IpSecForwardPolicyRequest in daemon.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package zy.hotspot.app.root.daemon

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.sanitize
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Suppress
import okio.ByteString

public class IpSecForwardPolicyRequest(
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#INT32",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 0,
  )
  public val uid: Int = 0,
  @field:WireField(
    tag = 2,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "sourceAddress",
    schemaIndex = 1,
  )
  public val source_address: String = "",
  @field:WireField(
    tag = 3,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "destinationAddress",
    schemaIndex = 2,
  )
  public val destination_address: String = "",
  @field:WireField(
    tag = 4,
    adapter = "com.squareup.wire.ProtoAdapter#INT32",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "markValue",
    schemaIndex = 3,
  )
  public val mark_value: Int = 0,
  @field:WireField(
    tag = 5,
    adapter = "com.squareup.wire.ProtoAdapter#INT32",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "xfrmInterfaceId",
    schemaIndex = 4,
  )
  public val xfrm_interface_id: Int = 0,
  unknownFields: ByteString = ByteString.EMPTY,
) : Message<IpSecForwardPolicyRequest, Nothing>(ADAPTER, unknownFields) {
  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is IpSecForwardPolicyRequest) return false
    if (unknownFields != other.unknownFields) return false
    if (uid != other.uid) return false
    if (source_address != other.source_address) return false
    if (destination_address != other.destination_address) return false
    if (mark_value != other.mark_value) return false
    if (xfrm_interface_id != other.xfrm_interface_id) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + uid.hashCode()
      result = result * 37 + source_address.hashCode()
      result = result * 37 + destination_address.hashCode()
      result = result * 37 + mark_value.hashCode()
      result = result * 37 + xfrm_interface_id.hashCode()
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    result += """uid=$uid"""
    result += """source_address=${sanitize(source_address)}"""
    result += """destination_address=${sanitize(destination_address)}"""
    result += """mark_value=$mark_value"""
    result += """xfrm_interface_id=$xfrm_interface_id"""
    return result.joinToString(prefix = "IpSecForwardPolicyRequest{", separator = ", ", postfix = "}")
  }

  public fun copy(
    uid: Int = this.uid,
    source_address: String = this.source_address,
    destination_address: String = this.destination_address,
    mark_value: Int = this.mark_value,
    xfrm_interface_id: Int = this.xfrm_interface_id,
    unknownFields: ByteString = this.unknownFields,
  ): IpSecForwardPolicyRequest = IpSecForwardPolicyRequest(uid, source_address, destination_address, mark_value, xfrm_interface_id, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<IpSecForwardPolicyRequest> =
        object : ProtoAdapter<IpSecForwardPolicyRequest>(
      FieldEncoding.LENGTH_DELIMITED, 
      IpSecForwardPolicyRequest::class, 
      "type.googleapis.com/vpnhotspot.daemon.IpSecForwardPolicyRequest", 
      PROTO_3, 
      null, 
      "daemon.proto"
    ) {
      override fun encodedSize(`value`: IpSecForwardPolicyRequest): Int {
        var size = value.unknownFields.size
        if (value.uid != 0) {
          size += ProtoAdapter.INT32.encodedSizeWithTag(1, value.uid)
        }
        if (value.source_address != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(2, value.source_address)
        }
        if (value.destination_address != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(3, value.destination_address)
        }
        if (value.mark_value != 0) {
          size += ProtoAdapter.INT32.encodedSizeWithTag(4, value.mark_value)
        }
        if (value.xfrm_interface_id != 0) {
          size += ProtoAdapter.INT32.encodedSizeWithTag(5, value.xfrm_interface_id)
        }
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: IpSecForwardPolicyRequest) {
        if (value.uid != 0) {
          ProtoAdapter.INT32.encodeWithTag(writer, 1, value.uid)
        }
        if (value.source_address != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 2, value.source_address)
        }
        if (value.destination_address != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 3, value.destination_address)
        }
        if (value.mark_value != 0) {
          ProtoAdapter.INT32.encodeWithTag(writer, 4, value.mark_value)
        }
        if (value.xfrm_interface_id != 0) {
          ProtoAdapter.INT32.encodeWithTag(writer, 5, value.xfrm_interface_id)
        }
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: IpSecForwardPolicyRequest) {
        writer.writeBytes(value.unknownFields)
        if (value.xfrm_interface_id != 0) {
          ProtoAdapter.INT32.encodeWithTag(writer, 5, value.xfrm_interface_id)
        }
        if (value.mark_value != 0) {
          ProtoAdapter.INT32.encodeWithTag(writer, 4, value.mark_value)
        }
        if (value.destination_address != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 3, value.destination_address)
        }
        if (value.source_address != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 2, value.source_address)
        }
        if (value.uid != 0) {
          ProtoAdapter.INT32.encodeWithTag(writer, 1, value.uid)
        }
      }

      override fun decode(reader: ProtoReader): IpSecForwardPolicyRequest {
        var uid: Int = 0
        var source_address: String = ""
        var destination_address: String = ""
        var mark_value: Int = 0
        var xfrm_interface_id: Int = 0
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> uid = ProtoAdapter.INT32.decode(reader)
            2 -> source_address = ProtoAdapter.STRING.decode(reader)
            3 -> destination_address = ProtoAdapter.STRING.decode(reader)
            4 -> mark_value = ProtoAdapter.INT32.decode(reader)
            5 -> xfrm_interface_id = ProtoAdapter.INT32.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return IpSecForwardPolicyRequest(
          uid = uid,
          source_address = source_address,
          destination_address = destination_address,
          mark_value = mark_value,
          xfrm_interface_id = xfrm_interface_id,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: IpSecForwardPolicyRequest): IpSecForwardPolicyRequest = value.copy(
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
