// Code generated by Wire protocol buffer compiler, do not edit.
// Source: vpnhotspot.daemon.Ipv6Prefix in daemon.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package zy.hotspot.app.root.daemon

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Suppress
import okio.ByteString

public class Ipv6Prefix(
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#BYTES",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 0,
  )
  public val address: ByteString = ByteString.EMPTY,
  @field:WireField(
    tag = 2,
    adapter = "com.squareup.wire.ProtoAdapter#UINT32",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "prefixLength",
    schemaIndex = 1,
  )
  public val prefix_length: Int = 0,
  unknownFields: ByteString = ByteString.EMPTY,
) : Message<Ipv6Prefix, Nothing>(ADAPTER, unknownFields) {
  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is Ipv6Prefix) return false
    if (unknownFields != other.unknownFields) return false
    if (address != other.address) return false
    if (prefix_length != other.prefix_length) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + address.hashCode()
      result = result * 37 + prefix_length.hashCode()
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    result += """address=$address"""
    result += """prefix_length=$prefix_length"""
    return result.joinToString(prefix = "Ipv6Prefix{", separator = ", ", postfix = "}")
  }

  public fun copy(
    address: ByteString = this.address,
    prefix_length: Int = this.prefix_length,
    unknownFields: ByteString = this.unknownFields,
  ): Ipv6Prefix = Ipv6Prefix(address, prefix_length, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<Ipv6Prefix> = object : ProtoAdapter<Ipv6Prefix>(
      FieldEncoding.LENGTH_DELIMITED, 
      Ipv6Prefix::class, 
      "type.googleapis.com/vpnhotspot.daemon.Ipv6Prefix", 
      PROTO_3, 
      null, 
      "daemon.proto"
    ) {
      override fun encodedSize(`value`: Ipv6Prefix): Int {
        var size = value.unknownFields.size
        if (value.address != okio.ByteString.EMPTY) {
          size += ProtoAdapter.BYTES.encodedSizeWithTag(1, value.address)
        }
        if (value.prefix_length != 0) {
          size += ProtoAdapter.UINT32.encodedSizeWithTag(2, value.prefix_length)
        }
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: Ipv6Prefix) {
        if (value.address != okio.ByteString.EMPTY) {
          ProtoAdapter.BYTES.encodeWithTag(writer, 1, value.address)
        }
        if (value.prefix_length != 0) {
          ProtoAdapter.UINT32.encodeWithTag(writer, 2, value.prefix_length)
        }
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: Ipv6Prefix) {
        writer.writeBytes(value.unknownFields)
        if (value.prefix_length != 0) {
          ProtoAdapter.UINT32.encodeWithTag(writer, 2, value.prefix_length)
        }
        if (value.address != okio.ByteString.EMPTY) {
          ProtoAdapter.BYTES.encodeWithTag(writer, 1, value.address)
        }
      }

      override fun decode(reader: ProtoReader): Ipv6Prefix {
        var address: ByteString = ByteString.EMPTY
        var prefix_length: Int = 0
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> address = ProtoAdapter.BYTES.decode(reader)
            2 -> prefix_length = ProtoAdapter.UINT32.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return Ipv6Prefix(
          address = address,
          prefix_length = prefix_length,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: Ipv6Prefix): Ipv6Prefix = value.copy(
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
