// Code generated by Wire protocol buffer compiler, do not edit.
// Source: vpnhotspot.daemon.LinkTopologySnapshot in daemon.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package zy.hotspot.app.root.daemon

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.immutableCopyOf
import com.squareup.wire.`internal`.redactElements
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Suppress
import kotlin.collections.List
import okio.ByteString

public class LinkTopologySnapshot(
  bridges: List<BridgeInterface> = emptyList(),
  unknownFields: ByteString = ByteString.EMPTY,
) : Message<LinkTopologySnapshot, Nothing>(ADAPTER, unknownFields) {
  @field:WireField(
    tag = 1,
    adapter = "zy.hotspot.app.root.daemon.BridgeInterface#ADAPTER",
    label = WireField.Label.REPEATED,
    schemaIndex = 0,
  )
  public val bridges: List<BridgeInterface> = immutableCopyOf("bridges", bridges)

  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is LinkTopologySnapshot) return false
    if (unknownFields != other.unknownFields) return false
    if (bridges != other.bridges) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + bridges.hashCode()
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    if (bridges.isNotEmpty()) result += """bridges=$bridges"""
    return result.joinToString(prefix = "LinkTopologySnapshot{", separator = ", ", postfix = "}")
  }

  public fun copy(bridges: List<BridgeInterface> = this.bridges, unknownFields: ByteString = this.unknownFields): LinkTopologySnapshot = LinkTopologySnapshot(bridges, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<LinkTopologySnapshot> =
        object : ProtoAdapter<LinkTopologySnapshot>(
      FieldEncoding.LENGTH_DELIMITED, 
      LinkTopologySnapshot::class, 
      "type.googleapis.com/vpnhotspot.daemon.LinkTopologySnapshot", 
      PROTO_3, 
      null, 
      "daemon.proto"
    ) {
      override fun encodedSize(`value`: LinkTopologySnapshot): Int {
        var size = value.unknownFields.size
        size += BridgeInterface.ADAPTER.asRepeated().encodedSizeWithTag(1, value.bridges)
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: LinkTopologySnapshot) {
        BridgeInterface.ADAPTER.asRepeated().encodeWithTag(writer, 1, value.bridges)
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: LinkTopologySnapshot) {
        writer.writeBytes(value.unknownFields)
        BridgeInterface.ADAPTER.asRepeated().encodeWithTag(writer, 1, value.bridges)
      }

      override fun decode(reader: ProtoReader): LinkTopologySnapshot {
        val bridges = mutableListOf<BridgeInterface>()
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> bridges.add(BridgeInterface.ADAPTER.decode(reader))
            else -> reader.readUnknownField(tag)
          }
        }
        return LinkTopologySnapshot(
          bridges = bridges,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: LinkTopologySnapshot): LinkTopologySnapshot = value.copy(
        bridges = value.bridges.redactElements(BridgeInterface.ADAPTER),
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
