// Code generated by Wire protocol buffer compiler, do not edit.
// Source: vpnhotspot.daemon.MasqueradeMode in daemon.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package zy.hotspot.app.root.daemon

import com.squareup.wire.EnumAdapter
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireEnum
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.JvmStatic
import kotlin.ConsistentCopyVisibility
import kotlin.Int
import kotlin.Suppress

public sealed class MasqueradeMode(
  override val `value`: Int,
) : WireEnum {
  public data object MASQUERADE_MODE_NONE : MasqueradeMode(0)

  public data object MASQUERADE_MODE_SIMPLE : MasqueradeMode(1)

  public data object MASQUERADE_MODE_NETD : MasqueradeMode(2)

  @ConsistentCopyVisibility
  public data class Unrecognized internal constructor(
    override val `value`: Int,
  ) : MasqueradeMode(value)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<MasqueradeMode> = object : EnumAdapter<MasqueradeMode>(
      MasqueradeMode::class, 
      PROTO_3, 
      MasqueradeMode.MASQUERADE_MODE_NONE
    ) {
      override fun fromValue(`value`: Int): MasqueradeMode? = MasqueradeMode.fromValue(`value`)
    }

    @JvmStatic
    public fun fromValue(`value`: Int): MasqueradeMode = when (`value`) {
      0 -> MASQUERADE_MODE_NONE
      1 -> MASQUERADE_MODE_SIMPLE
      2 -> MASQUERADE_MODE_NETD
      else -> Unrecognized(`value`)
    }
  }
}
