// Code generated by Wire protocol buffer compiler, do not edit.
// Source: vpnhotspot.daemon.Neighbour in daemon.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package zy.hotspot.app.root.daemon

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.sanitize
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Suppress
import okio.ByteString

public class Neighbour(
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#BYTES",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 0,
  )
  public val address: ByteString = ByteString.EMPTY,
  @field:WireField(
    tag = 2,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 1,
  )
  public val dev: String = "",
  @field:WireField(
    tag = 3,
    adapter = "com.squareup.wire.ProtoAdapter#BYTES",
    schemaIndex = 2,
  )
  public val lladdr: ByteString? = null,
  @field:WireField(
    tag = 4,
    adapter = "zy.hotspot.app.root.daemon.NeighbourState#ADAPTER",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 3,
  )
  public val state: NeighbourState = NeighbourState.NEIGHBOUR_STATE_UNSET,
  unknownFields: ByteString = ByteString.EMPTY,
) : Message<Neighbour, Nothing>(ADAPTER, unknownFields) {
  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is Neighbour) return false
    if (unknownFields != other.unknownFields) return false
    if (address != other.address) return false
    if (dev != other.dev) return false
    if (lladdr != other.lladdr) return false
    if (state != other.state) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + address.hashCode()
      result = result * 37 + dev.hashCode()
      result = result * 37 + (lladdr?.hashCode() ?: 0)
      result = result * 37 + state.hashCode()
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    result += """address=$address"""
    result += """dev=${sanitize(dev)}"""
    if (lladdr != null) result += """lladdr=$lladdr"""
    result += """state=$state"""
    return result.joinToString(prefix = "Neighbour{", separator = ", ", postfix = "}")
  }

  public fun copy(
    address: ByteString = this.address,
    dev: String = this.dev,
    lladdr: ByteString? = this.lladdr,
    state: NeighbourState = this.state,
    unknownFields: ByteString = this.unknownFields,
  ): Neighbour = Neighbour(address, dev, lladdr, state, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<Neighbour> = object : ProtoAdapter<Neighbour>(
      FieldEncoding.LENGTH_DELIMITED, 
      Neighbour::class, 
      "type.googleapis.com/vpnhotspot.daemon.Neighbour", 
      PROTO_3, 
      null, 
      "daemon.proto"
    ) {
      override fun encodedSize(`value`: Neighbour): Int {
        var size = value.unknownFields.size
        if (value.address != okio.ByteString.EMPTY) {
          size += ProtoAdapter.BYTES.encodedSizeWithTag(1, value.address)
        }
        if (value.dev != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(2, value.dev)
        }
        size += ProtoAdapter.BYTES.encodedSizeWithTag(3, value.lladdr)
        if (value.state != zy.hotspot.app.root.daemon.NeighbourState.NEIGHBOUR_STATE_UNSET) {
          size += NeighbourState.ADAPTER.encodedSizeWithTag(4, value.state)
        }
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: Neighbour) {
        if (value.address != okio.ByteString.EMPTY) {
          ProtoAdapter.BYTES.encodeWithTag(writer, 1, value.address)
        }
        if (value.dev != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 2, value.dev)
        }
        ProtoAdapter.BYTES.encodeWithTag(writer, 3, value.lladdr)
        if (value.state != zy.hotspot.app.root.daemon.NeighbourState.NEIGHBOUR_STATE_UNSET) {
          NeighbourState.ADAPTER.encodeWithTag(writer, 4, value.state)
        }
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: Neighbour) {
        writer.writeBytes(value.unknownFields)
        if (value.state != zy.hotspot.app.root.daemon.NeighbourState.NEIGHBOUR_STATE_UNSET) {
          NeighbourState.ADAPTER.encodeWithTag(writer, 4, value.state)
        }
        ProtoAdapter.BYTES.encodeWithTag(writer, 3, value.lladdr)
        if (value.dev != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 2, value.dev)
        }
        if (value.address != okio.ByteString.EMPTY) {
          ProtoAdapter.BYTES.encodeWithTag(writer, 1, value.address)
        }
      }

      override fun decode(reader: ProtoReader): Neighbour {
        var address: ByteString = ByteString.EMPTY
        var dev: String = ""
        var lladdr: ByteString? = null
        var state: NeighbourState = NeighbourState.NEIGHBOUR_STATE_UNSET
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> address = ProtoAdapter.BYTES.decode(reader)
            2 -> dev = ProtoAdapter.STRING.decode(reader)
            3 -> lladdr = ProtoAdapter.BYTES.decode(reader)
            4 -> try {
              state = NeighbourState.ADAPTER.decode(reader)
            } catch (e: ProtoAdapter.EnumConstantNotFoundException) {
              reader.addUnknownField(tag, FieldEncoding.VARINT, e.value.toLong())
            }
            else -> reader.readUnknownField(tag)
          }
        }
        return Neighbour(
          address = address,
          dev = dev,
          lladdr = lladdr,
          state = state,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: Neighbour): Neighbour = value.copy(
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
