// Code generated by Wire protocol buffer compiler, do not edit.
// Source: vpnhotspot.daemon.NeighbourMonitorUpdate in daemon.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package zy.hotspot.app.root.daemon

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.immutableCopyOf
import com.squareup.wire.`internal`.redactElements
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Suppress
import kotlin.collections.List
import okio.ByteString

public class NeighbourMonitorUpdate(
  neighbour_deltas: List<NeighbourDelta> = emptyList(),
  @field:WireField(
    tag = 2,
    adapter = "zy.hotspot.app.root.daemon.LinkTopologySnapshot#ADAPTER",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "linkTopology",
    schemaIndex = 1,
  )
  public val link_topology: LinkTopologySnapshot? = null,
  unknownFields: ByteString = ByteString.EMPTY,
) : Message<NeighbourMonitorUpdate, Nothing>(ADAPTER, unknownFields) {
  @field:WireField(
    tag = 1,
    adapter = "zy.hotspot.app.root.daemon.NeighbourDelta#ADAPTER",
    label = WireField.Label.REPEATED,
    jsonName = "neighbourDeltas",
    schemaIndex = 0,
  )
  public val neighbour_deltas: List<NeighbourDelta> =
      immutableCopyOf("neighbour_deltas", neighbour_deltas)

  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is NeighbourMonitorUpdate) return false
    if (unknownFields != other.unknownFields) return false
    if (neighbour_deltas != other.neighbour_deltas) return false
    if (link_topology != other.link_topology) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + neighbour_deltas.hashCode()
      result = result * 37 + (link_topology?.hashCode() ?: 0)
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    if (neighbour_deltas.isNotEmpty()) result += """neighbour_deltas=$neighbour_deltas"""
    if (link_topology != null) result += """link_topology=$link_topology"""
    return result.joinToString(prefix = "NeighbourMonitorUpdate{", separator = ", ", postfix = "}")
  }

  public fun copy(
    neighbour_deltas: List<NeighbourDelta> = this.neighbour_deltas,
    link_topology: LinkTopologySnapshot? = this.link_topology,
    unknownFields: ByteString = this.unknownFields,
  ): NeighbourMonitorUpdate = NeighbourMonitorUpdate(neighbour_deltas, link_topology, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<NeighbourMonitorUpdate> =
        object : ProtoAdapter<NeighbourMonitorUpdate>(
      FieldEncoding.LENGTH_DELIMITED, 
      NeighbourMonitorUpdate::class, 
      "type.googleapis.com/vpnhotspot.daemon.NeighbourMonitorUpdate", 
      PROTO_3, 
      null, 
      "daemon.proto"
    ) {
      override fun encodedSize(`value`: NeighbourMonitorUpdate): Int {
        var size = value.unknownFields.size
        size += NeighbourDelta.ADAPTER.asRepeated().encodedSizeWithTag(1, value.neighbour_deltas)
        if (value.link_topology != null) {
          size += LinkTopologySnapshot.ADAPTER.encodedSizeWithTag(2, value.link_topology)
        }
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: NeighbourMonitorUpdate) {
        NeighbourDelta.ADAPTER.asRepeated().encodeWithTag(writer, 1, value.neighbour_deltas)
        if (value.link_topology != null) {
          LinkTopologySnapshot.ADAPTER.encodeWithTag(writer, 2, value.link_topology)
        }
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: NeighbourMonitorUpdate) {
        writer.writeBytes(value.unknownFields)
        if (value.link_topology != null) {
          LinkTopologySnapshot.ADAPTER.encodeWithTag(writer, 2, value.link_topology)
        }
        NeighbourDelta.ADAPTER.asRepeated().encodeWithTag(writer, 1, value.neighbour_deltas)
      }

      override fun decode(reader: ProtoReader): NeighbourMonitorUpdate {
        val neighbour_deltas = mutableListOf<NeighbourDelta>()
        var link_topology: LinkTopologySnapshot? = null
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> neighbour_deltas.add(NeighbourDelta.ADAPTER.decode(reader))
            2 -> link_topology = LinkTopologySnapshot.ADAPTER.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return NeighbourMonitorUpdate(
          neighbour_deltas = neighbour_deltas,
          link_topology = link_topology,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: NeighbourMonitorUpdate): NeighbourMonitorUpdate = value.copy(
        neighbour_deltas = value.neighbour_deltas.redactElements(NeighbourDelta.ADAPTER),
        link_topology = value.link_topology?.let(LinkTopologySnapshot.ADAPTER::redact),
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
