// Code generated by Wire protocol buffer compiler, do not edit.
// Source: vpnhotspot.daemon.NeighbourState in daemon.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package zy.hotspot.app.root.daemon

import com.squareup.wire.EnumAdapter
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireEnum
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.JvmStatic
import kotlin.ConsistentCopyVisibility
import kotlin.Int
import kotlin.Suppress

public sealed class NeighbourState(
  override val `value`: Int,
) : WireEnum {
  public data object NEIGHBOUR_STATE_UNSET : NeighbourState(0)

  public data object NEIGHBOUR_STATE_INCOMPLETE : NeighbourState(1)

  public data object NEIGHBOUR_STATE_VALID : NeighbourState(2)

  public data object NEIGHBOUR_STATE_FAILED : NeighbourState(3)

  @ConsistentCopyVisibility
  public data class Unrecognized internal constructor(
    override val `value`: Int,
  ) : NeighbourState(value)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<NeighbourState> = object : EnumAdapter<NeighbourState>(
      NeighbourState::class, 
      PROTO_3, 
      NeighbourState.NEIGHBOUR_STATE_UNSET
    ) {
      override fun fromValue(`value`: Int): NeighbourState? = NeighbourState.fromValue(`value`)
    }

    @JvmStatic
    public fun fromValue(`value`: Int): NeighbourState = when (`value`) {
      0 -> NEIGHBOUR_STATE_UNSET
      1 -> NEIGHBOUR_STATE_INCOMPLETE
      2 -> NEIGHBOUR_STATE_VALID
      3 -> NEIGHBOUR_STATE_FAILED
      else -> Unrecognized(`value`)
    }
  }
}
