// Code generated by Wire protocol buffer compiler, do not edit.
// Source: vpnhotspot.daemon.NeighbourDelta in daemon.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package zy.hotspot.app.root.daemon

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.countNonNull
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Suppress
import okio.ByteString

public class NeighbourDelta(
  @field:WireField(
    tag = 1,
    adapter = "zy.hotspot.app.root.daemon.Neighbour#ADAPTER",
    oneofName = "delta",
    schemaIndex = 0,
  )
  public val upsert: Neighbour? = null,
  @field:WireField(
    tag = 2,
    adapter = "zy.hotspot.app.root.daemon.NeighbourDelete#ADAPTER",
    oneofName = "delta",
    schemaIndex = 1,
  )
  public val delete: NeighbourDelete? = null,
  unknownFields: ByteString = ByteString.EMPTY,
) : Message<NeighbourDelta, Nothing>(ADAPTER, unknownFields) {
  init {
    require(countNonNull(upsert, delete) <= 1) {
      "At most one of upsert, delete may be non-null"
    }
  }

  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is NeighbourDelta) return false
    if (unknownFields != other.unknownFields) return false
    if (upsert != other.upsert) return false
    if (delete != other.delete) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + (upsert?.hashCode() ?: 0)
      result = result * 37 + (delete?.hashCode() ?: 0)
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    if (upsert != null) result += """upsert=$upsert"""
    if (delete != null) result += """delete=$delete"""
    return result.joinToString(prefix = "NeighbourDelta{", separator = ", ", postfix = "}")
  }

  public fun copy(
    upsert: Neighbour? = this.upsert,
    delete: NeighbourDelete? = this.delete,
    unknownFields: ByteString = this.unknownFields,
  ): NeighbourDelta = NeighbourDelta(upsert, delete, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<NeighbourDelta> = object : ProtoAdapter<NeighbourDelta>(
      FieldEncoding.LENGTH_DELIMITED, 
      NeighbourDelta::class, 
      "type.googleapis.com/vpnhotspot.daemon.NeighbourDelta", 
      PROTO_3, 
      null, 
      "daemon.proto"
    ) {
      override fun encodedSize(`value`: NeighbourDelta): Int {
        var size = value.unknownFields.size
        size += Neighbour.ADAPTER.encodedSizeWithTag(1, value.upsert)
        size += NeighbourDelete.ADAPTER.encodedSizeWithTag(2, value.delete)
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: NeighbourDelta) {
        Neighbour.ADAPTER.encodeWithTag(writer, 1, value.upsert)
        NeighbourDelete.ADAPTER.encodeWithTag(writer, 2, value.delete)
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: NeighbourDelta) {
        writer.writeBytes(value.unknownFields)
        NeighbourDelete.ADAPTER.encodeWithTag(writer, 2, value.delete)
        Neighbour.ADAPTER.encodeWithTag(writer, 1, value.upsert)
      }

      override fun decode(reader: ProtoReader): NeighbourDelta {
        var upsert: Neighbour? = null
        var delete: NeighbourDelete? = null
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> upsert = Neighbour.ADAPTER.decode(reader)
            2 -> delete = NeighbourDelete.ADAPTER.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return NeighbourDelta(
          upsert = upsert,
          delete = delete,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: NeighbourDelta): NeighbourDelta = value.copy(
        upsert = value.upsert?.let(Neighbour.ADAPTER::redact),
        delete = value.delete?.let(NeighbourDelete.ADAPTER::redact),
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
