// Code generated by Wire protocol buffer compiler, do not edit.
// Source: vpnhotspot.daemon.NeighbourDelete in daemon.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package zy.hotspot.app.root.daemon

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.sanitize
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Suppress
import okio.ByteString

public class NeighbourDelete(
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#BYTES",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 0,
  )
  public val address: ByteString = ByteString.EMPTY,
  @field:WireField(
    tag = 2,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 1,
  )
  public val dev: String = "",
  unknownFields: ByteString = ByteString.EMPTY,
) : Message<NeighbourDelete, Nothing>(ADAPTER, unknownFields) {
  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is NeighbourDelete) return false
    if (unknownFields != other.unknownFields) return false
    if (address != other.address) return false
    if (dev != other.dev) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + address.hashCode()
      result = result * 37 + dev.hashCode()
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    result += """address=$address"""
    result += """dev=${sanitize(dev)}"""
    return result.joinToString(prefix = "NeighbourDelete{", separator = ", ", postfix = "}")
  }

  public fun copy(
    address: ByteString = this.address,
    dev: String = this.dev,
    unknownFields: ByteString = this.unknownFields,
  ): NeighbourDelete = NeighbourDelete(address, dev, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<NeighbourDelete> = object : ProtoAdapter<NeighbourDelete>(
      FieldEncoding.LENGTH_DELIMITED, 
      NeighbourDelete::class, 
      "type.googleapis.com/vpnhotspot.daemon.NeighbourDelete", 
      PROTO_3, 
      null, 
      "daemon.proto"
    ) {
      override fun encodedSize(`value`: NeighbourDelete): Int {
        var size = value.unknownFields.size
        if (value.address != okio.ByteString.EMPTY) {
          size += ProtoAdapter.BYTES.encodedSizeWithTag(1, value.address)
        }
        if (value.dev != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(2, value.dev)
        }
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: NeighbourDelete) {
        if (value.address != okio.ByteString.EMPTY) {
          ProtoAdapter.BYTES.encodeWithTag(writer, 1, value.address)
        }
        if (value.dev != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 2, value.dev)
        }
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: NeighbourDelete) {
        writer.writeBytes(value.unknownFields)
        if (value.dev != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 2, value.dev)
        }
        if (value.address != okio.ByteString.EMPTY) {
          ProtoAdapter.BYTES.encodeWithTag(writer, 1, value.address)
        }
      }

      override fun decode(reader: ProtoReader): NeighbourDelete {
        var address: ByteString = ByteString.EMPTY
        var dev: String = ""
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> address = ProtoAdapter.BYTES.decode(reader)
            2 -> dev = ProtoAdapter.STRING.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return NeighbourDelete(
          address = address,
          dev = dev,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: NeighbourDelete): NeighbourDelete = value.copy(
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
