// Code generated by Wire protocol buffer compiler, do not edit.
// Source: vpnhotspot.daemon.NonFatalFrame in daemon.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package zy.hotspot.app.root.daemon

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Suppress
import okio.ByteString

public class NonFatalFrame(
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#UINT64",
    jsonName = "callId",
    schemaIndex = 0,
  )
  public val call_id: Long? = null,
  @field:WireField(
    tag = 2,
    adapter = "zy.hotspot.app.root.daemon.DaemonErrorReport#ADAPTER",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 1,
  )
  public val report: DaemonErrorReport? = null,
  unknownFields: ByteString = ByteString.EMPTY,
) : Message<NonFatalFrame, Nothing>(ADAPTER, unknownFields) {
  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is NonFatalFrame) return false
    if (unknownFields != other.unknownFields) return false
    if (call_id != other.call_id) return false
    if (report != other.report) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + (call_id?.hashCode() ?: 0)
      result = result * 37 + (report?.hashCode() ?: 0)
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    if (call_id != null) result += """call_id=$call_id"""
    if (report != null) result += """report=$report"""
    return result.joinToString(prefix = "NonFatalFrame{", separator = ", ", postfix = "}")
  }

  public fun copy(
    call_id: Long? = this.call_id,
    report: DaemonErrorReport? = this.report,
    unknownFields: ByteString = this.unknownFields,
  ): NonFatalFrame = NonFatalFrame(call_id, report, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<NonFatalFrame> = object : ProtoAdapter<NonFatalFrame>(
      FieldEncoding.LENGTH_DELIMITED, 
      NonFatalFrame::class, 
      "type.googleapis.com/vpnhotspot.daemon.NonFatalFrame", 
      PROTO_3, 
      null, 
      "daemon.proto"
    ) {
      override fun encodedSize(`value`: NonFatalFrame): Int {
        var size = value.unknownFields.size
        size += ProtoAdapter.UINT64.encodedSizeWithTag(1, value.call_id)
        if (value.report != null) {
          size += DaemonErrorReport.ADAPTER.encodedSizeWithTag(2, value.report)
        }
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: NonFatalFrame) {
        ProtoAdapter.UINT64.encodeWithTag(writer, 1, value.call_id)
        if (value.report != null) {
          DaemonErrorReport.ADAPTER.encodeWithTag(writer, 2, value.report)
        }
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: NonFatalFrame) {
        writer.writeBytes(value.unknownFields)
        if (value.report != null) {
          DaemonErrorReport.ADAPTER.encodeWithTag(writer, 2, value.report)
        }
        ProtoAdapter.UINT64.encodeWithTag(writer, 1, value.call_id)
      }

      override fun decode(reader: ProtoReader): NonFatalFrame {
        var call_id: Long? = null
        var report: DaemonErrorReport? = null
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> call_id = ProtoAdapter.UINT64.decode(reader)
            2 -> report = DaemonErrorReport.ADAPTER.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return NonFatalFrame(
          call_id = call_id,
          report = report,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: NonFatalFrame): NonFatalFrame = value.copy(
        report = value.report?.let(DaemonErrorReport.ADAPTER::redact),
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
