// Code generated by Wire protocol buffer compiler, do not edit.
// Source: vpnhotspot.daemon.ReplaceSessionCommand in daemon.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package zy.hotspot.app.root.daemon

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Suppress
import okio.ByteString

public class ReplaceSessionCommand(
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#UINT64",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "sessionId",
    schemaIndex = 0,
  )
  public val session_id: Long = 0L,
  @field:WireField(
    tag = 2,
    adapter = "zy.hotspot.app.root.daemon.SessionConfig#ADAPTER",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 1,
  )
  public val config: SessionConfig? = null,
  unknownFields: ByteString = ByteString.EMPTY,
) : Message<ReplaceSessionCommand, Nothing>(ADAPTER, unknownFields) {
  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is ReplaceSessionCommand) return false
    if (unknownFields != other.unknownFields) return false
    if (session_id != other.session_id) return false
    if (config != other.config) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + session_id.hashCode()
      result = result * 37 + (config?.hashCode() ?: 0)
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    result += """session_id=$session_id"""
    if (config != null) result += """config=$config"""
    return result.joinToString(prefix = "ReplaceSessionCommand{", separator = ", ", postfix = "}")
  }

  public fun copy(
    session_id: Long = this.session_id,
    config: SessionConfig? = this.config,
    unknownFields: ByteString = this.unknownFields,
  ): ReplaceSessionCommand = ReplaceSessionCommand(session_id, config, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<ReplaceSessionCommand> =
        object : ProtoAdapter<ReplaceSessionCommand>(
      FieldEncoding.LENGTH_DELIMITED, 
      ReplaceSessionCommand::class, 
      "type.googleapis.com/vpnhotspot.daemon.ReplaceSessionCommand", 
      PROTO_3, 
      null, 
      "daemon.proto"
    ) {
      override fun encodedSize(`value`: ReplaceSessionCommand): Int {
        var size = value.unknownFields.size
        if (value.session_id != 0L) {
          size += ProtoAdapter.UINT64.encodedSizeWithTag(1, value.session_id)
        }
        if (value.config != null) {
          size += SessionConfig.ADAPTER.encodedSizeWithTag(2, value.config)
        }
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: ReplaceSessionCommand) {
        if (value.session_id != 0L) {
          ProtoAdapter.UINT64.encodeWithTag(writer, 1, value.session_id)
        }
        if (value.config != null) {
          SessionConfig.ADAPTER.encodeWithTag(writer, 2, value.config)
        }
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: ReplaceSessionCommand) {
        writer.writeBytes(value.unknownFields)
        if (value.config != null) {
          SessionConfig.ADAPTER.encodeWithTag(writer, 2, value.config)
        }
        if (value.session_id != 0L) {
          ProtoAdapter.UINT64.encodeWithTag(writer, 1, value.session_id)
        }
      }

      override fun decode(reader: ProtoReader): ReplaceSessionCommand {
        var session_id: Long = 0L
        var config: SessionConfig? = null
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> session_id = ProtoAdapter.UINT64.decode(reader)
            2 -> config = SessionConfig.ADAPTER.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return ReplaceSessionCommand(
          session_id = session_id,
          config = config,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: ReplaceSessionCommand): ReplaceSessionCommand = value.copy(
        config = value.config?.let(SessionConfig.ADAPTER::redact),
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
