// Code generated by Wire protocol buffer compiler, do not edit.
// Source: vpnhotspot.daemon.ReplyFrame in daemon.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package zy.hotspot.app.root.daemon

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.countNonNull
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Suppress
import okio.ByteString

public class ReplyFrame(
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#UINT64",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "callId",
    schemaIndex = 0,
  )
  public val call_id: Long = 0L,
  @field:WireField(
    tag = 2,
    adapter = "zy.hotspot.app.root.daemon.Ack#ADAPTER",
    oneofName = "payload",
    schemaIndex = 1,
  )
  public val ack: Ack? = null,
  @field:WireField(
    tag = 3,
    adapter = "zy.hotspot.app.root.daemon.TrafficCounters#ADAPTER",
    jsonName = "trafficCounters",
    oneofName = "payload",
    schemaIndex = 2,
  )
  public val traffic_counters: TrafficCounters? = null,
  unknownFields: ByteString = ByteString.EMPTY,
) : Message<ReplyFrame, Nothing>(ADAPTER, unknownFields) {
  init {
    require(countNonNull(ack, traffic_counters) <= 1) {
      "At most one of ack, traffic_counters may be non-null"
    }
  }

  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is ReplyFrame) return false
    if (unknownFields != other.unknownFields) return false
    if (call_id != other.call_id) return false
    if (ack != other.ack) return false
    if (traffic_counters != other.traffic_counters) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + call_id.hashCode()
      result = result * 37 + (ack?.hashCode() ?: 0)
      result = result * 37 + (traffic_counters?.hashCode() ?: 0)
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    result += """call_id=$call_id"""
    if (ack != null) result += """ack=$ack"""
    if (traffic_counters != null) result += """traffic_counters=$traffic_counters"""
    return result.joinToString(prefix = "ReplyFrame{", separator = ", ", postfix = "}")
  }

  public fun copy(
    call_id: Long = this.call_id,
    ack: Ack? = this.ack,
    traffic_counters: TrafficCounters? = this.traffic_counters,
    unknownFields: ByteString = this.unknownFields,
  ): ReplyFrame = ReplyFrame(call_id, ack, traffic_counters, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<ReplyFrame> = object : ProtoAdapter<ReplyFrame>(
      FieldEncoding.LENGTH_DELIMITED, 
      ReplyFrame::class, 
      "type.googleapis.com/vpnhotspot.daemon.ReplyFrame", 
      PROTO_3, 
      null, 
      "daemon.proto"
    ) {
      override fun encodedSize(`value`: ReplyFrame): Int {
        var size = value.unknownFields.size
        if (value.call_id != 0L) {
          size += ProtoAdapter.UINT64.encodedSizeWithTag(1, value.call_id)
        }
        size += Ack.ADAPTER.encodedSizeWithTag(2, value.ack)
        size += TrafficCounters.ADAPTER.encodedSizeWithTag(3, value.traffic_counters)
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: ReplyFrame) {
        if (value.call_id != 0L) {
          ProtoAdapter.UINT64.encodeWithTag(writer, 1, value.call_id)
        }
        Ack.ADAPTER.encodeWithTag(writer, 2, value.ack)
        TrafficCounters.ADAPTER.encodeWithTag(writer, 3, value.traffic_counters)
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: ReplyFrame) {
        writer.writeBytes(value.unknownFields)
        TrafficCounters.ADAPTER.encodeWithTag(writer, 3, value.traffic_counters)
        Ack.ADAPTER.encodeWithTag(writer, 2, value.ack)
        if (value.call_id != 0L) {
          ProtoAdapter.UINT64.encodeWithTag(writer, 1, value.call_id)
        }
      }

      override fun decode(reader: ProtoReader): ReplyFrame {
        var call_id: Long = 0L
        var ack: Ack? = null
        var traffic_counters: TrafficCounters? = null
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> call_id = ProtoAdapter.UINT64.decode(reader)
            2 -> ack = Ack.ADAPTER.decode(reader)
            3 -> traffic_counters = TrafficCounters.ADAPTER.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return ReplyFrame(
          call_id = call_id,
          ack = ack,
          traffic_counters = traffic_counters,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: ReplyFrame): ReplyFrame = value.copy(
        ack = value.ack?.let(Ack.ADAPTER::redact),
        traffic_counters = value.traffic_counters?.let(TrafficCounters.ADAPTER::redact),
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
