// Code generated by Wire protocol buffer compiler, do not edit.
// Source: vpnhotspot.daemon.SessionConfig in daemon.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package zy.hotspot.app.root.daemon

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.immutableCopyOf
import com.squareup.wire.`internal`.redactElements
import com.squareup.wire.`internal`.sanitize
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Suppress
import kotlin.collections.List
import okio.ByteString

public class SessionConfig(
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 0,
  )
  public val downstream: String = "",
  @field:WireField(
    tag = 2,
    adapter = "com.squareup.wire.ProtoAdapter#BOOL",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "ipForward",
    schemaIndex = 1,
  )
  public val ip_forward: Boolean = false,
  @field:WireField(
    tag = 3,
    adapter = "zy.hotspot.app.root.daemon.MasqueradeMode#ADAPTER",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 2,
  )
  public val masquerade: MasqueradeMode = MasqueradeMode.MASQUERADE_MODE_NONE,
  @field:WireField(
    tag = 4,
    adapter = "com.squareup.wire.ProtoAdapter#BOOL",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "ipv6Block",
    schemaIndex = 3,
  )
  public val ipv6_block: Boolean = false,
  @field:WireField(
    tag = 5,
    adapter = "com.squareup.wire.ProtoAdapter#UINT64",
    jsonName = "primaryNetwork",
    schemaIndex = 4,
  )
  public val primary_network: Long? = null,
  primary_routes: List<Ipv6Prefix> = emptyList(),
  @field:WireField(
    tag = 7,
    adapter = "com.squareup.wire.ProtoAdapter#UINT64",
    jsonName = "fallbackNetwork",
    schemaIndex = 6,
  )
  public val fallback_network: Long? = null,
  primary_upstream_interfaces: List<String> = emptyList(),
  fallback_upstream_interfaces: List<String> = emptyList(),
  clients: List<ClientConfig> = emptyList(),
  @field:WireField(
    tag = 11,
    adapter = "zy.hotspot.app.root.daemon.Ipv6NatConfig#ADAPTER",
    jsonName = "ipv6Nat",
    schemaIndex = 10,
  )
  public val ipv6_nat: Ipv6NatConfig? = null,
  @field:WireField(
    tag = 12,
    adapter = "com.squareup.wire.ProtoAdapter#UINT64",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "upstreamGeneration",
    schemaIndex = 11,
  )
  public val upstream_generation: Long = 0L,
  unknownFields: ByteString = ByteString.EMPTY,
) : Message<SessionConfig, Nothing>(ADAPTER, unknownFields) {
  @field:WireField(
    tag = 6,
    adapter = "zy.hotspot.app.root.daemon.Ipv6Prefix#ADAPTER",
    label = WireField.Label.REPEATED,
    jsonName = "primaryRoutes",
    schemaIndex = 5,
  )
  public val primary_routes: List<Ipv6Prefix> = immutableCopyOf("primary_routes", primary_routes)

  @field:WireField(
    tag = 8,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.REPEATED,
    jsonName = "primaryUpstreamInterfaces",
    schemaIndex = 7,
  )
  public val primary_upstream_interfaces: List<String> =
      immutableCopyOf("primary_upstream_interfaces", primary_upstream_interfaces)

  @field:WireField(
    tag = 9,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.REPEATED,
    jsonName = "fallbackUpstreamInterfaces",
    schemaIndex = 8,
  )
  public val fallback_upstream_interfaces: List<String> =
      immutableCopyOf("fallback_upstream_interfaces", fallback_upstream_interfaces)

  @field:WireField(
    tag = 10,
    adapter = "zy.hotspot.app.root.daemon.ClientConfig#ADAPTER",
    label = WireField.Label.REPEATED,
    schemaIndex = 9,
  )
  public val clients: List<ClientConfig> = immutableCopyOf("clients", clients)

  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is SessionConfig) return false
    if (unknownFields != other.unknownFields) return false
    if (downstream != other.downstream) return false
    if (ip_forward != other.ip_forward) return false
    if (masquerade != other.masquerade) return false
    if (ipv6_block != other.ipv6_block) return false
    if (primary_network != other.primary_network) return false
    if (primary_routes != other.primary_routes) return false
    if (fallback_network != other.fallback_network) return false
    if (primary_upstream_interfaces != other.primary_upstream_interfaces) return false
    if (fallback_upstream_interfaces != other.fallback_upstream_interfaces) return false
    if (clients != other.clients) return false
    if (ipv6_nat != other.ipv6_nat) return false
    if (upstream_generation != other.upstream_generation) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + downstream.hashCode()
      result = result * 37 + ip_forward.hashCode()
      result = result * 37 + masquerade.hashCode()
      result = result * 37 + ipv6_block.hashCode()
      result = result * 37 + (primary_network?.hashCode() ?: 0)
      result = result * 37 + primary_routes.hashCode()
      result = result * 37 + (fallback_network?.hashCode() ?: 0)
      result = result * 37 + primary_upstream_interfaces.hashCode()
      result = result * 37 + fallback_upstream_interfaces.hashCode()
      result = result * 37 + clients.hashCode()
      result = result * 37 + (ipv6_nat?.hashCode() ?: 0)
      result = result * 37 + upstream_generation.hashCode()
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    result += """downstream=${sanitize(downstream)}"""
    result += """ip_forward=$ip_forward"""
    result += """masquerade=$masquerade"""
    result += """ipv6_block=$ipv6_block"""
    if (primary_network != null) result += """primary_network=$primary_network"""
    if (primary_routes.isNotEmpty()) result += """primary_routes=$primary_routes"""
    if (fallback_network != null) result += """fallback_network=$fallback_network"""
    if (primary_upstream_interfaces.isNotEmpty()) result += """primary_upstream_interfaces=${sanitize(primary_upstream_interfaces)}"""
    if (fallback_upstream_interfaces.isNotEmpty()) result += """fallback_upstream_interfaces=${sanitize(fallback_upstream_interfaces)}"""
    if (clients.isNotEmpty()) result += """clients=$clients"""
    if (ipv6_nat != null) result += """ipv6_nat=$ipv6_nat"""
    result += """upstream_generation=$upstream_generation"""
    return result.joinToString(prefix = "SessionConfig{", separator = ", ", postfix = "}")
  }

  public fun copy(
    downstream: String = this.downstream,
    ip_forward: Boolean = this.ip_forward,
    masquerade: MasqueradeMode = this.masquerade,
    ipv6_block: Boolean = this.ipv6_block,
    primary_network: Long? = this.primary_network,
    primary_routes: List<Ipv6Prefix> = this.primary_routes,
    fallback_network: Long? = this.fallback_network,
    primary_upstream_interfaces: List<String> = this.primary_upstream_interfaces,
    fallback_upstream_interfaces: List<String> = this.fallback_upstream_interfaces,
    clients: List<ClientConfig> = this.clients,
    ipv6_nat: Ipv6NatConfig? = this.ipv6_nat,
    upstream_generation: Long = this.upstream_generation,
    unknownFields: ByteString = this.unknownFields,
  ): SessionConfig = SessionConfig(downstream, ip_forward, masquerade, ipv6_block, primary_network, primary_routes, fallback_network, primary_upstream_interfaces, fallback_upstream_interfaces, clients, ipv6_nat, upstream_generation, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<SessionConfig> = object : ProtoAdapter<SessionConfig>(
      FieldEncoding.LENGTH_DELIMITED, 
      SessionConfig::class, 
      "type.googleapis.com/vpnhotspot.daemon.SessionConfig", 
      PROTO_3, 
      null, 
      "daemon.proto"
    ) {
      override fun encodedSize(`value`: SessionConfig): Int {
        var size = value.unknownFields.size
        if (value.downstream != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(1, value.downstream)
        }
        if (value.ip_forward != false) {
          size += ProtoAdapter.BOOL.encodedSizeWithTag(2, value.ip_forward)
        }
        if (value.masquerade != zy.hotspot.app.root.daemon.MasqueradeMode.MASQUERADE_MODE_NONE) {
          size += MasqueradeMode.ADAPTER.encodedSizeWithTag(3, value.masquerade)
        }
        if (value.ipv6_block != false) {
          size += ProtoAdapter.BOOL.encodedSizeWithTag(4, value.ipv6_block)
        }
        size += ProtoAdapter.UINT64.encodedSizeWithTag(5, value.primary_network)
        size += Ipv6Prefix.ADAPTER.asRepeated().encodedSizeWithTag(6, value.primary_routes)
        size += ProtoAdapter.UINT64.encodedSizeWithTag(7, value.fallback_network)
        size += ProtoAdapter.STRING.asRepeated().encodedSizeWithTag(8, value.primary_upstream_interfaces)
        size += ProtoAdapter.STRING.asRepeated().encodedSizeWithTag(9, value.fallback_upstream_interfaces)
        size += ClientConfig.ADAPTER.asRepeated().encodedSizeWithTag(10, value.clients)
        size += Ipv6NatConfig.ADAPTER.encodedSizeWithTag(11, value.ipv6_nat)
        if (value.upstream_generation != 0L) {
          size += ProtoAdapter.UINT64.encodedSizeWithTag(12, value.upstream_generation)
        }
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: SessionConfig) {
        if (value.downstream != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 1, value.downstream)
        }
        if (value.ip_forward != false) {
          ProtoAdapter.BOOL.encodeWithTag(writer, 2, value.ip_forward)
        }
        if (value.masquerade != zy.hotspot.app.root.daemon.MasqueradeMode.MASQUERADE_MODE_NONE) {
          MasqueradeMode.ADAPTER.encodeWithTag(writer, 3, value.masquerade)
        }
        if (value.ipv6_block != false) {
          ProtoAdapter.BOOL.encodeWithTag(writer, 4, value.ipv6_block)
        }
        ProtoAdapter.UINT64.encodeWithTag(writer, 5, value.primary_network)
        Ipv6Prefix.ADAPTER.asRepeated().encodeWithTag(writer, 6, value.primary_routes)
        ProtoAdapter.UINT64.encodeWithTag(writer, 7, value.fallback_network)
        ProtoAdapter.STRING.asRepeated().encodeWithTag(writer, 8, value.primary_upstream_interfaces)
        ProtoAdapter.STRING.asRepeated().encodeWithTag(writer, 9, value.fallback_upstream_interfaces)
        ClientConfig.ADAPTER.asRepeated().encodeWithTag(writer, 10, value.clients)
        Ipv6NatConfig.ADAPTER.encodeWithTag(writer, 11, value.ipv6_nat)
        if (value.upstream_generation != 0L) {
          ProtoAdapter.UINT64.encodeWithTag(writer, 12, value.upstream_generation)
        }
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: SessionConfig) {
        writer.writeBytes(value.unknownFields)
        if (value.upstream_generation != 0L) {
          ProtoAdapter.UINT64.encodeWithTag(writer, 12, value.upstream_generation)
        }
        Ipv6NatConfig.ADAPTER.encodeWithTag(writer, 11, value.ipv6_nat)
        ClientConfig.ADAPTER.asRepeated().encodeWithTag(writer, 10, value.clients)
        ProtoAdapter.STRING.asRepeated().encodeWithTag(writer, 9, value.fallback_upstream_interfaces)
        ProtoAdapter.STRING.asRepeated().encodeWithTag(writer, 8, value.primary_upstream_interfaces)
        ProtoAdapter.UINT64.encodeWithTag(writer, 7, value.fallback_network)
        Ipv6Prefix.ADAPTER.asRepeated().encodeWithTag(writer, 6, value.primary_routes)
        ProtoAdapter.UINT64.encodeWithTag(writer, 5, value.primary_network)
        if (value.ipv6_block != false) {
          ProtoAdapter.BOOL.encodeWithTag(writer, 4, value.ipv6_block)
        }
        if (value.masquerade != zy.hotspot.app.root.daemon.MasqueradeMode.MASQUERADE_MODE_NONE) {
          MasqueradeMode.ADAPTER.encodeWithTag(writer, 3, value.masquerade)
        }
        if (value.ip_forward != false) {
          ProtoAdapter.BOOL.encodeWithTag(writer, 2, value.ip_forward)
        }
        if (value.downstream != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 1, value.downstream)
        }
      }

      override fun decode(reader: ProtoReader): SessionConfig {
        var downstream: String = ""
        var ip_forward: Boolean = false
        var masquerade: MasqueradeMode = MasqueradeMode.MASQUERADE_MODE_NONE
        var ipv6_block: Boolean = false
        var primary_network: Long? = null
        val primary_routes = mutableListOf<Ipv6Prefix>()
        var fallback_network: Long? = null
        val primary_upstream_interfaces = mutableListOf<String>()
        val fallback_upstream_interfaces = mutableListOf<String>()
        val clients = mutableListOf<ClientConfig>()
        var ipv6_nat: Ipv6NatConfig? = null
        var upstream_generation: Long = 0L
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> downstream = ProtoAdapter.STRING.decode(reader)
            2 -> ip_forward = ProtoAdapter.BOOL.decode(reader)
            3 -> try {
              masquerade = MasqueradeMode.ADAPTER.decode(reader)
            } catch (e: ProtoAdapter.EnumConstantNotFoundException) {
              reader.addUnknownField(tag, FieldEncoding.VARINT, e.value.toLong())
            }
            4 -> ipv6_block = ProtoAdapter.BOOL.decode(reader)
            5 -> primary_network = ProtoAdapter.UINT64.decode(reader)
            6 -> primary_routes.add(Ipv6Prefix.ADAPTER.decode(reader))
            7 -> fallback_network = ProtoAdapter.UINT64.decode(reader)
            8 -> primary_upstream_interfaces.add(ProtoAdapter.STRING.decode(reader))
            9 -> fallback_upstream_interfaces.add(ProtoAdapter.STRING.decode(reader))
            10 -> clients.add(ClientConfig.ADAPTER.decode(reader))
            11 -> ipv6_nat = Ipv6NatConfig.ADAPTER.decode(reader)
            12 -> upstream_generation = ProtoAdapter.UINT64.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return SessionConfig(
          downstream = downstream,
          ip_forward = ip_forward,
          masquerade = masquerade,
          ipv6_block = ipv6_block,
          primary_network = primary_network,
          primary_routes = primary_routes,
          fallback_network = fallback_network,
          primary_upstream_interfaces = primary_upstream_interfaces,
          fallback_upstream_interfaces = fallback_upstream_interfaces,
          clients = clients,
          ipv6_nat = ipv6_nat,
          upstream_generation = upstream_generation,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: SessionConfig): SessionConfig = value.copy(
        primary_routes = value.primary_routes.redactElements(Ipv6Prefix.ADAPTER),
        clients = value.clients.redactElements(ClientConfig.ADAPTER),
        ipv6_nat = value.ipv6_nat?.let(Ipv6NatConfig.ADAPTER::redact),
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
