// Code generated by Wire protocol buffer compiler, do not edit.
// Source: vpnhotspot.daemon.StartSessionCommand in daemon.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package zy.hotspot.app.root.daemon

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Suppress
import okio.ByteString

public class StartSessionCommand(
  @field:WireField(
    tag = 1,
    adapter = "zy.hotspot.app.root.daemon.SessionConfig#ADAPTER",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 0,
  )
  public val config: SessionConfig? = null,
  unknownFields: ByteString = ByteString.EMPTY,
) : Message<StartSessionCommand, Nothing>(ADAPTER, unknownFields) {
  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is StartSessionCommand) return false
    if (unknownFields != other.unknownFields) return false
    if (config != other.config) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + (config?.hashCode() ?: 0)
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    if (config != null) result += """config=$config"""
    return result.joinToString(prefix = "StartSessionCommand{", separator = ", ", postfix = "}")
  }

  public fun copy(config: SessionConfig? = this.config, unknownFields: ByteString = this.unknownFields): StartSessionCommand = StartSessionCommand(config, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<StartSessionCommand> =
        object : ProtoAdapter<StartSessionCommand>(
      FieldEncoding.LENGTH_DELIMITED, 
      StartSessionCommand::class, 
      "type.googleapis.com/vpnhotspot.daemon.StartSessionCommand", 
      PROTO_3, 
      null, 
      "daemon.proto"
    ) {
      override fun encodedSize(`value`: StartSessionCommand): Int {
        var size = value.unknownFields.size
        if (value.config != null) {
          size += SessionConfig.ADAPTER.encodedSizeWithTag(1, value.config)
        }
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: StartSessionCommand) {
        if (value.config != null) {
          SessionConfig.ADAPTER.encodeWithTag(writer, 1, value.config)
        }
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: StartSessionCommand) {
        writer.writeBytes(value.unknownFields)
        if (value.config != null) {
          SessionConfig.ADAPTER.encodeWithTag(writer, 1, value.config)
        }
      }

      override fun decode(reader: ProtoReader): StartSessionCommand {
        var config: SessionConfig? = null
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> config = SessionConfig.ADAPTER.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return StartSessionCommand(
          config = config,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: StartSessionCommand): StartSessionCommand = value.copy(
        config = value.config?.let(SessionConfig.ADAPTER::redact),
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
