// Code generated by Wire protocol buffer compiler, do not edit.
// Source: vpnhotspot.daemon.TrafficCounter in daemon.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package zy.hotspot.app.root.daemon

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.sanitize
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Suppress
import okio.ByteString

public class TrafficCounter(
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#BYTES",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 0,
  )
  public val mac: ByteString = ByteString.EMPTY,
  @field:WireField(
    tag = 2,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 1,
  )
  public val downstream: String = "",
  @field:WireField(
    tag = 3,
    adapter = "zy.hotspot.app.root.daemon.TrafficCounterSource#ADAPTER",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 2,
  )
  public val source: TrafficCounterSource? = null,
  @field:WireField(
    tag = 4,
    adapter = "com.squareup.wire.ProtoAdapter#UINT64",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "sentPackets",
    schemaIndex = 3,
  )
  public val sent_packets: Long = 0L,
  @field:WireField(
    tag = 5,
    adapter = "com.squareup.wire.ProtoAdapter#UINT64",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "sentBytes",
    schemaIndex = 4,
  )
  public val sent_bytes: Long = 0L,
  @field:WireField(
    tag = 6,
    adapter = "com.squareup.wire.ProtoAdapter#UINT64",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "receivedPackets",
    schemaIndex = 5,
  )
  public val received_packets: Long = 0L,
  @field:WireField(
    tag = 7,
    adapter = "com.squareup.wire.ProtoAdapter#UINT64",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "receivedBytes",
    schemaIndex = 6,
  )
  public val received_bytes: Long = 0L,
  unknownFields: ByteString = ByteString.EMPTY,
) : Message<TrafficCounter, Nothing>(ADAPTER, unknownFields) {
  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is TrafficCounter) return false
    if (unknownFields != other.unknownFields) return false
    if (mac != other.mac) return false
    if (downstream != other.downstream) return false
    if (source != other.source) return false
    if (sent_packets != other.sent_packets) return false
    if (sent_bytes != other.sent_bytes) return false
    if (received_packets != other.received_packets) return false
    if (received_bytes != other.received_bytes) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + mac.hashCode()
      result = result * 37 + downstream.hashCode()
      result = result * 37 + (source?.hashCode() ?: 0)
      result = result * 37 + sent_packets.hashCode()
      result = result * 37 + sent_bytes.hashCode()
      result = result * 37 + received_packets.hashCode()
      result = result * 37 + received_bytes.hashCode()
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    result += """mac=$mac"""
    result += """downstream=${sanitize(downstream)}"""
    if (source != null) result += """source=$source"""
    result += """sent_packets=$sent_packets"""
    result += """sent_bytes=$sent_bytes"""
    result += """received_packets=$received_packets"""
    result += """received_bytes=$received_bytes"""
    return result.joinToString(prefix = "TrafficCounter{", separator = ", ", postfix = "}")
  }

  public fun copy(
    mac: ByteString = this.mac,
    downstream: String = this.downstream,
    source: TrafficCounterSource? = this.source,
    sent_packets: Long = this.sent_packets,
    sent_bytes: Long = this.sent_bytes,
    received_packets: Long = this.received_packets,
    received_bytes: Long = this.received_bytes,
    unknownFields: ByteString = this.unknownFields,
  ): TrafficCounter = TrafficCounter(mac, downstream, source, sent_packets, sent_bytes, received_packets, received_bytes, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<TrafficCounter> = object : ProtoAdapter<TrafficCounter>(
      FieldEncoding.LENGTH_DELIMITED, 
      TrafficCounter::class, 
      "type.googleapis.com/vpnhotspot.daemon.TrafficCounter", 
      PROTO_3, 
      null, 
      "daemon.proto"
    ) {
      override fun encodedSize(`value`: TrafficCounter): Int {
        var size = value.unknownFields.size
        if (value.mac != okio.ByteString.EMPTY) {
          size += ProtoAdapter.BYTES.encodedSizeWithTag(1, value.mac)
        }
        if (value.downstream != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(2, value.downstream)
        }
        if (value.source != null) {
          size += TrafficCounterSource.ADAPTER.encodedSizeWithTag(3, value.source)
        }
        if (value.sent_packets != 0L) {
          size += ProtoAdapter.UINT64.encodedSizeWithTag(4, value.sent_packets)
        }
        if (value.sent_bytes != 0L) {
          size += ProtoAdapter.UINT64.encodedSizeWithTag(5, value.sent_bytes)
        }
        if (value.received_packets != 0L) {
          size += ProtoAdapter.UINT64.encodedSizeWithTag(6, value.received_packets)
        }
        if (value.received_bytes != 0L) {
          size += ProtoAdapter.UINT64.encodedSizeWithTag(7, value.received_bytes)
        }
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: TrafficCounter) {
        if (value.mac != okio.ByteString.EMPTY) {
          ProtoAdapter.BYTES.encodeWithTag(writer, 1, value.mac)
        }
        if (value.downstream != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 2, value.downstream)
        }
        if (value.source != null) {
          TrafficCounterSource.ADAPTER.encodeWithTag(writer, 3, value.source)
        }
        if (value.sent_packets != 0L) {
          ProtoAdapter.UINT64.encodeWithTag(writer, 4, value.sent_packets)
        }
        if (value.sent_bytes != 0L) {
          ProtoAdapter.UINT64.encodeWithTag(writer, 5, value.sent_bytes)
        }
        if (value.received_packets != 0L) {
          ProtoAdapter.UINT64.encodeWithTag(writer, 6, value.received_packets)
        }
        if (value.received_bytes != 0L) {
          ProtoAdapter.UINT64.encodeWithTag(writer, 7, value.received_bytes)
        }
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: TrafficCounter) {
        writer.writeBytes(value.unknownFields)
        if (value.received_bytes != 0L) {
          ProtoAdapter.UINT64.encodeWithTag(writer, 7, value.received_bytes)
        }
        if (value.received_packets != 0L) {
          ProtoAdapter.UINT64.encodeWithTag(writer, 6, value.received_packets)
        }
        if (value.sent_bytes != 0L) {
          ProtoAdapter.UINT64.encodeWithTag(writer, 5, value.sent_bytes)
        }
        if (value.sent_packets != 0L) {
          ProtoAdapter.UINT64.encodeWithTag(writer, 4, value.sent_packets)
        }
        if (value.source != null) {
          TrafficCounterSource.ADAPTER.encodeWithTag(writer, 3, value.source)
        }
        if (value.downstream != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 2, value.downstream)
        }
        if (value.mac != okio.ByteString.EMPTY) {
          ProtoAdapter.BYTES.encodeWithTag(writer, 1, value.mac)
        }
      }

      override fun decode(reader: ProtoReader): TrafficCounter {
        var mac: ByteString = ByteString.EMPTY
        var downstream: String = ""
        var source: TrafficCounterSource? = null
        var sent_packets: Long = 0L
        var sent_bytes: Long = 0L
        var received_packets: Long = 0L
        var received_bytes: Long = 0L
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> mac = ProtoAdapter.BYTES.decode(reader)
            2 -> downstream = ProtoAdapter.STRING.decode(reader)
            3 -> source = TrafficCounterSource.ADAPTER.decode(reader)
            4 -> sent_packets = ProtoAdapter.UINT64.decode(reader)
            5 -> sent_bytes = ProtoAdapter.UINT64.decode(reader)
            6 -> received_packets = ProtoAdapter.UINT64.decode(reader)
            7 -> received_bytes = ProtoAdapter.UINT64.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return TrafficCounter(
          mac = mac,
          downstream = downstream,
          source = source,
          sent_packets = sent_packets,
          sent_bytes = sent_bytes,
          received_packets = received_packets,
          received_bytes = received_bytes,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: TrafficCounter): TrafficCounter = value.copy(
        source = value.source?.let(TrafficCounterSource.ADAPTER::redact),
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
