// Code generated by Wire protocol buffer compiler, do not edit.
// Source: vpnhotspot.daemon.TrafficCounterSource in daemon.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package zy.hotspot.app.root.daemon

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.countNonNull
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Suppress
import okio.ByteString

public class TrafficCounterSource(
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#BYTES",
    jsonName = "ipv4ForwardAddress",
    oneofName = "source",
    schemaIndex = 0,
  )
  public val ipv4_forward_address: ByteString? = null,
  @field:WireField(
    tag = 2,
    adapter = "zy.hotspot.app.root.daemon.DaemonTrafficSource#ADAPTER",
    jsonName = "daemonSource",
    oneofName = "source",
    schemaIndex = 1,
  )
  public val daemon_source: DaemonTrafficSource? = null,
  unknownFields: ByteString = ByteString.EMPTY,
) : Message<TrafficCounterSource, Nothing>(ADAPTER, unknownFields) {
  init {
    require(countNonNull(ipv4_forward_address, daemon_source) <= 1) {
      "At most one of ipv4_forward_address, daemon_source may be non-null"
    }
  }

  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is TrafficCounterSource) return false
    if (unknownFields != other.unknownFields) return false
    if (ipv4_forward_address != other.ipv4_forward_address) return false
    if (daemon_source != other.daemon_source) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + (ipv4_forward_address?.hashCode() ?: 0)
      result = result * 37 + (daemon_source?.hashCode() ?: 0)
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    if (ipv4_forward_address != null) result += """ipv4_forward_address=$ipv4_forward_address"""
    if (daemon_source != null) result += """daemon_source=$daemon_source"""
    return result.joinToString(prefix = "TrafficCounterSource{", separator = ", ", postfix = "}")
  }

  public fun copy(
    ipv4_forward_address: ByteString? = this.ipv4_forward_address,
    daemon_source: DaemonTrafficSource? = this.daemon_source,
    unknownFields: ByteString = this.unknownFields,
  ): TrafficCounterSource = TrafficCounterSource(ipv4_forward_address, daemon_source, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<TrafficCounterSource> =
        object : ProtoAdapter<TrafficCounterSource>(
      FieldEncoding.LENGTH_DELIMITED, 
      TrafficCounterSource::class, 
      "type.googleapis.com/vpnhotspot.daemon.TrafficCounterSource", 
      PROTO_3, 
      null, 
      "daemon.proto"
    ) {
      override fun encodedSize(`value`: TrafficCounterSource): Int {
        var size = value.unknownFields.size
        size += ProtoAdapter.BYTES.encodedSizeWithTag(1, value.ipv4_forward_address)
        size += DaemonTrafficSource.ADAPTER.encodedSizeWithTag(2, value.daemon_source)
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: TrafficCounterSource) {
        ProtoAdapter.BYTES.encodeWithTag(writer, 1, value.ipv4_forward_address)
        DaemonTrafficSource.ADAPTER.encodeWithTag(writer, 2, value.daemon_source)
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: TrafficCounterSource) {
        writer.writeBytes(value.unknownFields)
        DaemonTrafficSource.ADAPTER.encodeWithTag(writer, 2, value.daemon_source)
        ProtoAdapter.BYTES.encodeWithTag(writer, 1, value.ipv4_forward_address)
      }

      override fun decode(reader: ProtoReader): TrafficCounterSource {
        var ipv4_forward_address: ByteString? = null
        var daemon_source: DaemonTrafficSource? = null
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> ipv4_forward_address = ProtoAdapter.BYTES.decode(reader)
            2 -> try {
              daemon_source = DaemonTrafficSource.ADAPTER.decode(reader)
            } catch (e: ProtoAdapter.EnumConstantNotFoundException) {
              reader.addUnknownField(tag, FieldEncoding.VARINT, e.value.toLong())
            }
            else -> reader.readUnknownField(tag)
          }
        }
        return TrafficCounterSource(
          ipv4_forward_address = ipv4_forward_address,
          daemon_source = daemon_source,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: TrafficCounterSource): TrafficCounterSource = value.copy(
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
